Repository corda/corda, pull requests merged in 2018-09, with the labels that each got.

#3873 CORDA-1837: Reject nodes that have the same organisation name in driver tests
  testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: Backport

#3894 Tidy up DemoBench's fallback logging configuration for JUL.
  tools/demobench/src/main/java/net/corda/demobench/config/LoggingConfig.java
Labels: trivial

#3895 ENT-1906: Remove SLF4J's JUL logging bridge from DJVM.
  djvm/build.gradle
  djvm/cli/build.gradle
  djvm/cli/src/main/resources/log4j2.xml
Labels: trivial

#3872 CORDA-1755: Modify the node to run using picocli
  docs/source/running-a-node.rst
  node/build.gradle
  node/src/main/java/CordaCaplet.java
  node/src/main/kotlin/net/corda/node/Corda.kt
  node/src/main/kotlin/net/corda/node/NodeArgsParser.kt
  node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
  node/src/test/kotlin/net/corda/node/NodeArgsParserTest.kt
  node/src/test/kotlin/net/corda/node/NodeCmdLineOptionsTest.kt
  tools/bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt
  tools/cliutils/build.gradle
  tools/cliutils/src/main/kotlin/net/corda/cliutils/ConfigFilePathArgsParser.kt
  tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
  tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaVersionProvider.kt
  tools/cliutils/src/main/kotlin/net/corda/cliutils/ExitCodes.kt
  tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt
Labels: enhancement

#3686 CORDA-1760 CLI UX guidelines
  docs/source/cli-ux-guidelines.rst
  docs/source/contributing-index.rst
  docs/source/contributing.rst
Labels: documentation

#3866 CORDA-1803 - Fix variable replacement (#3585)
  docs/source/conf.py
Labels: Backport

#3875 CORDA-1952 Fix duplicate index declaration. (#3779)
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt
Labels: Backport

#3891 Updated repository lists to reduce dependency on Jitpack and removed …
  build.gradle
  docs/source/example-code/build.gradle
  experimental/build.gradle
  tools/explorer/build.gradle
  tools/explorer/capsule/build.gradle
Labels: Backport

#3916 CORDA-1875: backport tweaks made to RPC client for handling loss of node
  client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
  node/src/test/kotlin/net/corda/node/services/rpc/ArtemisRpcTests.kt
  samples/irs-demo/web/src/main/kotlin/net/corda/irs/web/IrsDemoWebApplication.kt
  webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
Labels: Backport

#3912 Record Hikari metrics
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/DataSourceFactory.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Labels: enhancement

#3913 Use standard Automatic-Module-Name for DemoBench.
  tools/demobench/build.gradle
Labels: trivial

#3921 CORDA-1093 Deleting node info from directory (#3115)
  node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
  node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
  node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
Labels: Backport

#3935 CORDA-1976 Fix flaky test
  node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt
Labels: bug

#3928 CORDA-1892 CRaSH shell flow start fix for similar flow names. (#3874)
  node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
Labels: Backport

#3883 Cherry-pick [CORDA-1572] Create marker file to track initial registration status.…
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Labels: Backport

#3865 CORDA-1548 - Hibernate session not flushed before handing over raw JDBC session to user code (e.g. coin selection) (#3266)
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
Labels: Backport

#3919 CORDA-1949, CORDA-1950 - Miscellaneous doc fixes (#3760)
  docs/source/hello-world-flow.rst
  docs/source/hello-world-running.rst
  docs/source/hello-world-template.rst
Labels: Backport

#3939 CORDA-1959 - Enforce backwards compatibility of new CLI's
  node/build.gradle
  node/src/main/resources/net.corda.node.internal.NodeStartup.yml
  node/src/test/kotlin/net/corda/node/internal/NodeStartupCompatibilityTest.kt
  testing/test-cli/src/main/kotlin/net/corda/testing/CliBackwardsCompatibleTest.kt
  testing/test-cli/src/main/kotlin/net/corda/testing/CommandLineCompatibilityUtils.kt
  tools/bootstrapper/build.gradle
  tools/bootstrapper/src/test/kotlin/net/corda/bootstrapper/NetworkBootstrapperRunnerTest.kt
  tools/bootstrapper/src/test/resources/net.corda.bootstrapper.NetworkBootstrapperRunner.yml
  tools/shell-cli/build.gradle
  tools/shell-cli/src/test/kotlin/net/corda/tools/shell/StandaloneShellCompatibilityTest.kt
  tools/shell-cli/src/test/resources/net.corda.tools.shell.StandaloneShell.yml
Labels: tests

#3945 RELEASE - Release script to extract which issues are in a release
  release-tools/jiraReleaseChecker.py
Labels: Release

#3949 CORDA-1985: Configure Gradle capsule plugin to use Capsule 1.0.3.
  build.gradle
  node/capsule/build.gradle
  tools/explorer/capsule/build.gradle
  webserver/webcapsule/build.gradle
Labels: enhancement

#3954 RELEASE - Script to identity and format commits added to the branch
  release-tools/jiraReleaseChecker.py
Labels: Backport, Release

#3956 [CORDA-1971]: Improve error code derivation
  node/src/main/kotlin/net/corda/node/internal/ExceptionsHashFunction.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Labels: enhancement

#3937 Backport fix for new identity causing node to crash
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
  node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
Labels: Backport

#3969 Backport Corda-1945 class-carpenter bugfix
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenterTest.kt
Labels: Backport

#3970 CORDA-1995 Removing DigitalSignatureWithCertPath (Cherry Pick)
  client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
  core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
Labels: Backport

#3977 CORDA-2001: backport SNI header
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt
Labels: Backport

#3992 [CORDA-1948]: Demobench profile load fails with stack dump -- for Corda OS 3.3 -- branch release-V3 (fix)
  tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeRpcSettings.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
  tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
  tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
Labels: Backport

#3991 CORDA-2012 truststore copy
  node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
  node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
Labels: Backport

#4000 ENT-1906: Upgrade DJVM to use ASM 6.2.1.
  djvm/build.gradle
  djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt
Labels: enhancement
