Repository corda/corda, pull requests merged in 2018-06, with the labels that each got.

#3303 [CORDA-1297] Columns nullability (#3112) -> V3
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/schemas/CommonSchema.kt
  core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt
  docs/source/changelog.rst
  docs/source/upgrade-notes.rst
  finance/src/main/kotlin/net/corda/finance/schemas/CashSchemaV1.kt
  finance/src/main/kotlin/net/corda/finance/schemas/CommercialPaperSchemaV1.kt
  finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt
  finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV2.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV3.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV1.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV2.kt
  node/src/integration-test/kotlin/net/corda/testMessage/MessageState.kt
  node/src/main/kotlin/net/corda/node/internal/schemas/NodeInfoSchema.kt
  node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
  node/src/main/kotlin/net/corda/node/services/events/PersistentScheduledFlowRepository.kt
  node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
  node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
  node/src/main/kotlin/net/corda/node/services/messaging/P2PMessageDeduplicator.kt
  node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt
  node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
  node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
  node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
  node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt
  node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV1.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV2.kt
Labels: Backport

#3300 [CORDA-1356]: OOM when using Demobench + Explorer (fix). (#3268)
  docs/source/changelog.rst
  tools/explorer/capsule/build.gradle
Labels: Backport

#3311 CORDA-1266 When a cash output is identical only the first output is saved. (#3244) -> V3
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
  node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Labels: Backport

#3310 CORDA-1499 Fix a typo in node_attchments_contracts table name. -> V3
  docs/source/changelog.rst
  docs/source/upgrade-notes.rst
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
Labels: Backport

#3346 ENT-1463, ENT-1903: Fix references in the documentation.
  docs/source/deterministic-modules.rst
Labels: bug

#3367 ENT-1463, ENT-1903: Raise minimum JDK to 8u171 to fix ZIP compression bugs,
  build.gradle
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/DummyJar.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt
Labels: bug

#3387 ENT-1463, ENT-1903: Refactor Gradle for deterministic modules
  core-deterministic/build.gradle
  core-deterministic/testing/common/build.gradle
  deterministic.gradle
  jdk8u-deterministic/build.gradle
  serialization-deterministic/build.gradle
Labels: enhancement

#3383 ENT-1463: Upgrade to Kotlin 1.2.50
  .ci/api-current.txt
  build.gradle
  constants.properties
  core/src/main/kotlin/net/corda/core/contracts/Attachment.kt
  core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
Labels: enhancement

#3399 CORDA-1645: Checkpoint before calling an idempotent sub-flow.
  core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt
  core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/IdempotentFlowTests.kt
Labels: bug

#3420 Upgrade to Gradle 4.8.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#3421 CORDA-1639: Resolve ProviderMismatchException when copying a file into a ZIP.
  core/src/main/kotlin/net/corda/core/internal/PathUtils.kt
  core/src/test/kotlin/net/corda/core/internal/PathUtilsTest.kt
Labels: bug

#3391 [CORDA-1498] serialization multiple transform bug
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/NotSerializableExceptions.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/TransformTypes.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/TransformsSchema.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumEvolvabilityTests.kt
Labels: Backport

#3427 CORDA-1662 - Corda Serialization Evolution breaksdown with Java classes
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationHelper.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenter.kt
  serialization/src/test/java/net/corda/serialization/internal/amqp/JavaEvolutionTests.java
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/StaticInitialisationOfSerializedObjectTest.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/CarpenterExceptionTests.kt
  serialization/src/test/resources/net/corda/serialization/internal/amqp/JavaEvolutionTests.testN1AddsNullableInt
  serialization/src/test/resources/net/corda/serialization/internal/amqp/JavaEvolutionTests.testN2AddsPrimitive
Labels: bug

#3438 Fix warning for lambda.
  core-deterministic/testing/common/src/main/kotlin/net/corda/deterministic/common/TransactionVerificationRequest.kt
Labels: trivial

#3446 CORDA-1685: Remove `bank-of-corda.jar` from DemoBench.
  tools/demobench/build.gradle
  tools/demobench/src/main/kotlin/net/corda/demobench/plugin/CordappController.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/profile/ProfileController.kt
  tools/explorer/capsule/build.gradle
Labels: bug

#3452 ENT-2145: Configure DemoBench nodes to issue selected currencies.
  tools/demobench/build.gradle
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
  tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
Labels: bug

#3457 CORDA-1686: Make Node Explorer release its RPC connection on shutdown.
  client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
  tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
  tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt
Labels: bug

#3468 CORDA-1693: Ensure that DemoBench's RPC connections terminate on shutdown.
  tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
Labels: bug
