Repository corda/corda, pull requests merged in 2018-10, with the labels that each got.

#4003 CORDA-2037 - Add network bootstrapper and other tools to published binary list
  build.gradle
  tools/blobinspector/build.gradle
  tools/bootstrapper/build.gradle
Labels: Backport

#4018 [Cherry-Pick] CORDA-2016 Add unit tests to ensure SNI header generation will not be changed by accident
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelperTest.kt
Labels: Backport, bug

#4023 [CORDA-2019]: Bootstrapper docs should not include --dir switch (fixed)
  docs/source/network-bootstrapper.rst
Labels: Backport

#3948 Release v3.3 docs
  .idea/compiler.xml
  docs/source/changelog.rst
  docs/source/release-notes.rst
  docs/source/upgrade-notes.rst
Labels: Release, work in progress

#4034 [CHERRY-PICK] CORDA-2071 Log file filling with Artemis messages and rolling over quickly
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/ConnectionChange.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt
  node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
Labels: Backport

#4043 CORDA-2030: Resolve build warnings about kotlin-stdlib-jre8 in unit tests too.
  confidential-identities/build.gradle
  core/build.gradle
Labels: bug

#4063 ENT-1906: Fix JavaDoc error for DJVM.
  djvm/src/main/java/sandbox/java/lang/ThreadLocal.java
Labels: bug

#4073 CORDA-2030: Prevent kotlin-stdlib-jre8 from becoming an accidental transitive dependency.
  node/build.gradle
Labels: bug

#4085 RELEASE - Merge 3.3 upgrade / notes / changelog back to master
  docs/source/changelog.rst
  docs/source/release-notes.rst
  docs/source/upgrade-notes.rst
Labels: Release

#4086 CORDA-2113 - Include PNM ID in CSR
  .idea/compiler.xml
  docs/source/corda-configuration-file.rst
  node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
  node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt
  node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: enhancement

#4083 CORDA-2111: Upgrade to Kotlin 1.2.71.
  constants.properties
Labels: enhancement

#4103 ENT-1906: Allow sandboxes to share a parent classloader.
  djvm/build.gradle
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistGenerateCommand.kt
  djvm/src/main/java/sandbox/java/lang/Object.java
  djvm/src/main/java/sandbox/java/lang/String.java
  djvm/src/main/java/sandbox/java/lang/System.java
  djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt
  djvm/src/main/kotlin/net/corda/djvm/SandboxRuntimeContext.kt
  djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
  djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt
  djvm/src/main/kotlin/net/corda/djvm/messages/MessageCollection.kt
  djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
  djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoadingException.kt
  djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
  djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
  djvm/src/test/java/net/corda/djvm/execution/SandboxEnumJavaTest.java
  djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java
  djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt
  djvm/src/test/kotlin/net/corda/djvm/DJVMTest.kt
  djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
  djvm/src/test/kotlin/net/corda/djvm/Utilities.kt
  djvm/src/test/kotlin/net/corda/djvm/assertions/AssertionExtensions.kt
  djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveClassWithByteCode.kt
  djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveDJVMObject.kt
  djvm/src/test/kotlin/net/corda/djvm/execution/SandboxEnumTest.kt
  djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
  djvm/src/test/kotlin/net/corda/djvm/execution/SandboxThrowableTest.kt
  djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt
Labels: enhancement

#4123 NOTICK - Enable generation of test tickets for snapshots
  release-tools/testing/README.md
  release-tools/testing/jira_manager.py
  release-tools/testing/test-manager
Labels: enhancement

#4128 CORDA-1633 - Check Java version before launch
  node/src/main/java/CordaCaplet.java
Labels: enhancement

#4131 CORDA-2109: Fix a bug that prevents consecutive multiparty contract upgrades
  core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
  node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV3.kt
Labels: Backport
