Repository corda/corda, pull requests merged in 2018-04, with the labels that each got.

#2903 ENT-1463: Instantiate the contract class as part of contract verification.
  core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
Labels: bug

#2912 CORDA-1276: Cleaned up creation of node-info object on node start and…
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
  node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
Labels: Backport

#2933 RELEASE: update vno for release testing
  build.gradle
Labels: Release

#2936 CORDA-1301: Upgrade to corda-gradle-plugins 4.0.11
  constants.properties
Labels: bug

#2938 [CORDA-1292] Add CordaService testing documentation and improve tests…
  docs/source/api-persistence.rst
  docs/source/api-testing.rst
  docs/source/oracles.rst
  samples/irs-demo/cordapp/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt
  samples/irs-demo/cordapp/src/test/kotlin/net/corda/irs/api/NodeInterestRatesTest.kt
  samples/irs-demo/cordapp/src/test/kotlin/net/corda/irs/api/OracleNodeTearOffTests.kt
Labels: Backport

#2952 REVERT - CORDA-1264 - Needs more thought prior to release
  .ci/api-current.txt
  client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/PermissionException.kt
  core/src/main/kotlin/net/corda/core/Utils.kt
  core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/InternalNodeException.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/OutdatedNetworkParameterHashException.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RejectedCommandException.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RpcSerializableError.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/adapters/InternalObfuscatingFlowHandle.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/adapters/InternalObfuscatingFlowProgressHandle.kt
  node/src/integration-test/kotlin/net/corda/ClientRelevantException.kt
  node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
  node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt
  node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/internal/RpcExceptionHandlingProxy.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
Labels: Release

#2937 Pre release v3.1 releasenote
  docs/source/changelog.rst
  docs/source/release-notes.rst
  docs/source/upgrade-notes.rst
Labels: Release

#2918 CORDA-1299: Upgrade to H2 1.4.197.
  build.gradle
  docs/source/changelog.rst
Labels: enhancement

#2968 Corda Behave extensions for CTS
  core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
  experimental/behave/README.md
  experimental/behave/build.gradle
  experimental/behave/deps/corda/3.0.0/.gitkeep
  experimental/behave/deps/corda/3.0.0/apps/.gitkeep
  experimental/behave/deps/drivers/README.md
  experimental/behave/prepare.sh
  experimental/behave/src/main/kotlin/net/corda/behave/database/DatabaseSettings.kt
  experimental/behave/src/main/kotlin/net/corda/behave/database/DatabaseType.kt
  experimental/behave/src/main/kotlin/net/corda/behave/database/configuration/PostgresConfigurationTemplate.kt
  experimental/behave/src/main/kotlin/net/corda/behave/file/FileUtilities.kt
  experimental/behave/src/main/kotlin/net/corda/behave/monitoring/ConjunctiveWatch.kt
  experimental/behave/src/main/kotlin/net/corda/behave/monitoring/DisjunctiveWatch.kt
  experimental/behave/src/main/kotlin/net/corda/behave/monitoring/PatternWatch.kt
  experimental/behave/src/main/kotlin/net/corda/behave/monitoring/Watch.kt
  experimental/behave/src/main/kotlin/net/corda/behave/network/Network.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/Distribution.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/Node.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/configuration/Configuration.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/configuration/CordappConfiguration.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/configuration/CurrencyConfiguration.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/configuration/NetworkInterface.kt
  experimental/behave/src/main/kotlin/net/corda/behave/node/configuration/NotaryConfiguration.kt
  experimental/behave/src/main/kotlin/net/corda/behave/process/Command.kt
  experimental/behave/src/main/kotlin/net/corda/behave/process/JarCommand.kt
  experimental/behave/src/main/kotlin/net/corda/behave/service/ContainerService.kt
  experimental/behave/src/main/kotlin/net/corda/behave/service/database/PostgreSQLService.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/ScenarioHooks.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/ScenarioRunner.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/ScenarioState.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/StepsBlock.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/StepsContainer.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/api/StepsBlock.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/api/StepsProvider.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Cash.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Startup.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Substeps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Vault.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/CashSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/ConfigurationSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/DatabaseSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/NetworkSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/RpcSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/SshSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/StartupSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/VaultSteps.kt
  experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/tests/StepsProviderTests.kt
  experimental/behave/src/scenario/resources/features/cash/currencies.feature
  experimental/behave/src/scenario/resources/features/database/connection.feature
  experimental/behave/src/scenario/resources/features/startup/logging.feature
  experimental/behave/src/test/kotlin/net/corda/behave/monitoring/MonitoringTests.kt
  experimental/behave/src/test/kotlin/net/corda/behave/network/NetworkTests.kt
  experimental/behave/src/test/kotlin/net/corda/behave/process/CommandTests.kt
  experimental/behave/src/test/kotlin/net/corda/behave/service/PostreSQLServiceTests.kt
Labels: enhancement

#2871 CORDA-1265: Upgrade to Kotlin language/API 1.2
  .ci/api-current.txt
  build.gradle
Labels: enhancement

#2992 CORDA-1263: Replace deprecated Kotlin artifacts.
  client/jfx/build.gradle
  core/build.gradle
  experimental/behave/build.gradle
  experimental/kryo-hook/build.gradle
  experimental/quasar-hook/build.gradle
  node-api/build.gradle
  node/build.gradle
  samples/attachment-demo/build.gradle
  samples/bank-of-corda-demo/build.gradle
  samples/notary-demo/build.gradle
  samples/simm-valuation-demo/build.gradle
  samples/trader-demo/build.gradle
  testing/test-utils/build.gradle
  tools/explorer/build.gradle
Labels: enhancement

#3033 Configure Gradle's wrapper task.
  build.gradle
Labels: enhancement
