Repository corda/corda, pull requests merged in 2018-03, with the labels that each got.

#2698 [CORDA-1136] Update startup message of P2P address and port
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
Labels: bug

#2700 RELEASE: Bump platform version
  constants.properties
Labels: Release

#2701 RELEASE: Bump platform version past V3
  constants.properties
Labels: Release

#2665 CORDA-1115 - Cannot serialize private nested objects
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/FingerPrinter.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
  samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
Labels: bug

#2692 CORDA-1134 - Don't use private serializes for all caps public properties
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
Labels: bug

#2708 CORDA-1134 - Don't use private serializers for all CAPS properties
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
Labels: Backport

#2710 Fix another non-serializable exception, add docs, fix a possible security issue.
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/CordaInternal.kt
  core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
Labels: Backport

#2709 CORDA-1115 - Cannot serialize private nested objects
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
  samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
Labels: Backport

#2699 Corda-1136: startup messages
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
Labels: bug

#2716 CORDA-1140 - FOR RPC Client P2P context use AMQP
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/KryoClientSerializationScheme.kt
  core/src/test/kotlin/net/corda/core/utilities/KotlinUtilsTest.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ServerContexts.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SharedContexts.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt
Labels: bug

#2735 REVIEW: Update version number for RC02
  build.gradle
Labels: Release

#2741 CORDA-1140 - RPC Client's P2P Context should use AMQP
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/KryoClientSerializationScheme.kt
  core/src/test/kotlin/net/corda/core/utilities/KotlinUtilsTest.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ServerContexts.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SharedContexts.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt
Labels: Backport

#2742 CORDA-1145 - V3 - troubleshooting rst
  docs/source/troubleshooting.rst
Labels: Backport

#2743 CORDA-1173 V3 SwapIdentityFlow doc fixes
  confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
  confidential-identities/src/main/kotlin/net/corda/confidential/SwapIdentitiesFlow.kt
  docs/source/api-identity.rst
Labels: Backport

#2747 CORDA-1175 V3 counterparty consistency
  confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
  core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
  core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
  docs/source/api-flows.rst
  docs/source/flow-library.rst
  docs/source/tutorial-cordapp.rst
  node/src/main/kotlin/net/corda/node/internal/StartedNode.kt
  samples/simm-valuation-demo/README.md
Labels: Backport

#2752 [CORDA-1167] Sort field annotations in public API and remove unnecessary @JvmField.
  .ci/api-current.txt
  constants.properties
Labels: bug, enhancement

#2606 Alter column names to be consistent with R3.Corda.
  node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt
Labels: Backport

#2760 CORDA-1186 - Move ConstructorForDeserialization out of internal
  node-api/src/main/kotlin/net/corda/core/serialization/ConstructorForDeserialization.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaSerializationOutputTests.java
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationPropertyOrdering.kt
Labels: Backport

#2764 CORDA-1117 - V3 - node-explorer.rst port fixes
  docs/source/node-explorer.rst
Labels: Backport

#2766 CORDA-1092 - V3 - fix secureRandomBytes
  core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
  core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
Labels: Backport

#2769 CORDA-1192 - Quieten message when reflecting on kotlin builtin
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializers.kt
Labels: Backport

#2492 V3 Release notes
  docs/source/changelog.rst
  docs/source/clientrpc.rst
  docs/source/release-notes.rst
Labels: Release

#2774 RELEASE: Update version number for RC03
  build.gradle
Labels: Release

#2550 Upgrade notes for V3.0
  docs/source/changelog.rst
  docs/source/upgrade-notes.rst
Labels: Release

#2781 CORDA-1186 - Actually move annotation into core module, not just core namespace
  core/src/main/kotlin/net/corda/core/serialization/ConstructorForDeserialization.kt
Labels: bug

#2794 CORDA-966 - RELEASE - Final release note tweeks
  docs/source/release-notes.rst
Labels: Release

#2799 RELEASE: Fix version number for the docs site
  docs/source/conf.py
Labels: Release

#2808 RELEASE: Post cut vno update
  build.gradle
Labels: Release

#2775 CORDA-966 - RELEASE - Merge release notes from release branch to master
  docs/source/changelog.rst
  docs/source/clientrpc.rst
  docs/source/release-notes.rst
Labels: Backport, Release

#2815 Upgrade to corda-gradle-plugins 4.0.8
  .ci/api-current.txt
  constants.properties
Labels: bug

#2847 CORDA-1224: Remove @JvmStatic annotations.
  .ci/api-current.txt
  constants.properties
Labels: enhancement

#2864 Remove repeated code
  node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
Labels: contribution

#2877 ENT-1665 - Update fast-classpath-scanner version to 2.12.3 (was 2.0.21)
  docs/source/changelog.rst
  node-api/build.gradle
Labels: bug

#2880 Ent-1665 - Upgrade fast-classpath-scanner from 2.0.21 to 2.12.3
  docs/source/changelog.rst
  node-api/build.gradle
Labels: Backport

#2881 ENT-1564 - add additional uploader check to the HashConstraint (#2845)
  core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
  core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoader.kt
  verifier/src/integration-test/kotlin/net/corda/verifier/VerifierTests.kt
Labels: Backport, bug

#2888 DOCS: Serialization roundtrip removes mutability explanation
  docs/source/serialization.rst
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/RoundTripTests.kt
Labels: Backport

#2872 Optimize imports
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
Labels: contribution

#2896 ENT-1686: Improve error message on parameters mismatch
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
Labels: Backport

#2900 BACKPORT: Generate a PDF version of the docsite. Request from a user in Slack.
  docs/Makefile
  docs/make-docsite.sh
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
Labels: Backport

#2899 Make JPA entities non-final and Serializable.
  .ci/api-current.txt
  build.gradle
  core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt
  node/src/main/kotlin/net/corda/node/internal/schemas/NodeInfoSchema.kt
  node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
  node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
  node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
  node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt
  node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
  node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
  node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt
  node/src/test/kotlin/net/corda/node/services/schema/NodeSchemaServiceTest.kt
Labels: Backport

#2897 ENT-1668: Don't crash on node startup when network map is not available
  docs/source/changelog.rst
  node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
Labels: Backport

#2901 Improve the upgrade-test-packages.sh script to work on macOS. Fixes a…
  tools/scripts/upgrade-test-packages.sh
Labels: Backport

#2902 [CORDA-1264]: Ensure correct serialisation and masking for throwables raised by a node and propagated through RPC.
  .ci/api-current.txt
  client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/PermissionException.kt
  core/src/main/kotlin/net/corda/core/Utils.kt
  core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/InternalNodeException.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/OutdatedNetworkParameterHashException.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RejectedCommandException.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RpcSerializableError.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/adapters/InternalObfuscatingFlowHandle.kt
  node-api/src/main/kotlin/net/corda/nodeapi/exceptions/adapters/InternalObfuscatingFlowProgressHandle.kt
  node/src/integration-test/kotlin/net/corda/ClientRelevantException.kt
  node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
  node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt
  node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/internal/RpcExceptionHandlingProxy.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
Labels: Backport
