Repository corda/corda, pull requests merged in 2018-07, with the labels that each got.

#3481 Rename JarFilter's ClassTransformer to FilterTransformer.
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/FieldRemovalTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/StaticFieldRemovalTest.kt
Labels: trivial

#3487 CORDA-1530 - Generics break default evolver (#3232)
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.addMandatoryFieldWithAltConstructorForceReorder
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.moreComplexNonNullWithReorder
Labels: Backport

#3485 CORDA-1510 - Allow Doorman and NetworkMap to be configured independently
  docs/source/changelog.rst
  docs/source/corda-configuration-file.rst
  docs/source/example-code/src/main/resources/example-node-with-networkservices.conf
  docs/source/permissioning.rst
  node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
  node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
  node/src/main/kotlin/net/corda/node/ArgsParser.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Labels: Backport

#3493 CORDA-1711 - Remove dependency on PathUtilsKt in net.corda.core.internal
  finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt
Labels: bug

#3492 CORDA-1711 - Remove dependency on PathUtilsKt in net.corda.core.internal
  finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt
Labels: Backport, bug

#3494 CORDA-1510 - Allow Doorman and NetworkMap to be configured independently
  docs/source/changelog.rst
  docs/source/corda-configuration-file.rst
  docs/source/example-code/src/main/resources/example-node-with-networkservices.conf
  docs/source/permissioning.rst
  node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
  node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
  node/src/main/kotlin/net/corda/node/ArgsParser.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Labels: Backport

#3496 backport bootstrapper to 3.2
  .idea/compiler.xml
  settings.gradle
  tools/network-bootstrapper/build.gradle
  tools/network-bootstrapper/src/main/java/net/corda/bootstrapper/GuiUtils.java
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/Constants.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/NetworkBuilder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/backends/AzureBackend.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/backends/Backend.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/backends/DockerBackend.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/cli/CommandLineInterface.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/cli/CommandParsers.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/InstanceInfo.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/Instantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/azure/AzureInstantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/docker/DockerInstantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/ContainerPusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/azure/AzureContainerPusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/azure/AzureRegistryLocator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/docker/DockerContainerPusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/context/Context.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/docker/DockerUtils.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/gui/BootstrapperView.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/gui/Gui.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/BuiltNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/CopiedNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/FoundNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeAdder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeBuilder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeCopier.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeFinder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeInstance.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeInstanceRequest.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeInstantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodePusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/PushedNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/notaries/CopiedNotary.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/notaries/NotaryCopier.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/notaries/NotaryFinder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/serialization/SerializationHelper.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/Volume.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/azure/AzureSmbVolume.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/docker/LocalVolume.kt
  tools/network-bootstrapper/src/main/resources/node-Dockerfile
  tools/network-bootstrapper/src/main/resources/node_info_watcher.sh
  tools/network-bootstrapper/src/main/resources/node_killer.sh
  tools/network-bootstrapper/src/main/resources/notary-Dockerfile
  tools/network-bootstrapper/src/main/resources/rpc-settings.conf
  tools/network-bootstrapper/src/main/resources/run-corda-node.sh
  tools/network-bootstrapper/src/main/resources/run-corda-notary.sh
  tools/network-bootstrapper/src/main/resources/ssh.conf
  tools/network-bootstrapper/src/main/resources/views/bootstrapper.css
  tools/network-bootstrapper/src/main/resources/views/cordalogo.png
  tools/network-bootstrapper/src/main/resources/views/mainPane.fxml
Labels: Backport

#3495 CORDA-1711 - Remove dependency on PathUtilsKt in net.corda.core.internal
  finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt
Labels: Backport, bug

#3489 CORDA-866, ENT-1933 backport event horizon + serialization fixes
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
  docs/source/network-map.rst
  docs/source/serialization-default-evolution.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
  node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
  node/src/test/resources/network-compatibility/network-parameters
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
  testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
Labels: Backport

#3503 CORDA-1709: Backporting an MVP blob inspector able to inspect network service blobs
  .ci/api-current.txt
  .idea/compiler.xml
  build.gradle
  client/jackson/build.gradle
  client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt
  client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt
  client/jackson/src/main/kotlin/net/corda/client/jackson/internal/JacksonUtils.kt
  client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
  client/jackson/src/test/resources/net/corda/client/jackson/class-not-on-classpath-data
  core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
  core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
  docs/source/blob-inspector.rst
  docs/source/changelog.rst
  docs/source/shell.rst
  docs/source/tools-index.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
  node/build.gradle
  node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
  node/src/test/kotlin/net/corda/node/shell/CustomTypeJsonParsingTests.kt
  samples/irs-demo/web/src/test/resources/net/corda/irs/web/simulation/trade.json
  settings.gradle
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/TestNodeInfoBuilder.kt
  tools/blobinspector/build.gradle
  tools/blobinspector/src/main/kotlin/net/corda/blobinspector/Main.kt
  tools/blobinspector/src/main/resources/log4j2.xml
Labels: Backport

#3499 CORDA-1704: Suppress ProGuard's "note" output
  buildSrc/jarfilter/kotlin-metadata/build.gradle
  core-deterministic/build.gradle
  core/src/main/kotlin/net/corda/core/flows/StateMachineRunId.kt
  core/src/main/kotlin/net/corda/core/internal/FlowStateMachine.kt
  serialization-deterministic/build.gradle
  serialization/src/main/kotlin/net/corda/serialization/internal/OrdinalIO.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformTypes.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformsSchema.kt
Labels: bug

#3511 Clear some cut-and-paste cruft out of our Gradle files.
  experimental/avalanche/build.gradle
  experimental/behave/build.gradle
  experimental/build.gradle
  experimental/kryo-hook/build.gradle
  experimental/quasar-hook/build.gradle
  samples/irs-demo/build.gradle
  tools/network-bootstrapper/build.gradle
Labels: trivial

#3509 CORDA-1723: Upgrade to Kotlin 1.2.51.
  build.gradle
  constants.properties
Labels: enhancement

#3521 Resolve warnings for constructing Kotlin ByteArray.
  client/mock/src/main/kotlin/net/corda/client/mock/EventGenerator.kt
  core-deterministic/testing/data/src/test/kotlin/net/corda/deterministic/data/KeyStoreGenerator.kt
  core-deterministic/testing/src/test/kotlin/net/corda/deterministic/contracts/PrivacySaltTest.kt
  core-deterministic/testing/src/test/kotlin/net/corda/deterministic/crypto/SecureHashTest.kt
  core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
  node/src/test/kotlin/net/corda/node/serialization/kryo/KryoTests.kt
  tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
Labels: trivial

#3505 CORDA-1699: Restore binary compatibility for UniqueIdentifier class.
  buildSrc/build.gradle
  buildSrc/jarfilter/README.md
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/KotlinAwareVisitor.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteConstructorTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseConstructorTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/JavaMatchers.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/KotlinMatchers.kt
  buildSrc/jarfilter/src/test/resources/sanitise-constructor/build.gradle
  buildSrc/jarfilter/src/test/resources/sanitise-constructor/kotlin/net/corda/gradle/HasOverloadedConstructors.kt
  core-deterministic/build.gradle
  core-deterministic/testing/build.gradle
  core-deterministic/testing/src/test/kotlin/net/corda/deterministic/contracts/UniqueIdentifierTest.kt
  core/src/main/kotlin/net/corda/core/contracts/UniqueIdentifier.kt
  docs/source/deterministic-modules.rst
  serialization-deterministic/build.gradle
Labels: bug

#3541 CORDA-1747 - External serializes break for generic types
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CorDappCustomSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/CorDappSerializerTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/testutils/AMQPTestUtils.kt
Labels: bug

#3542 CORDA-1699: Remove parameter defaults from Kotlin constructor metadata
  buildSrc/jarfilter/kotlin-metadata/build.gradle
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseDeleteConstructorTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseStubConstructorTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt
  buildSrc/jarfilter/src/test/resources/sanitise-constructor/kotlin/net/corda/gradle/HasOverloadedConstructors.kt
  buildSrc/jarfilter/src/test/resources/sanitise-delete-constructor/build.gradle
  buildSrc/jarfilter/src/test/resources/sanitise-delete-constructor/kotlin/net/corda/gradle/HasOverloadedConstructorsToDelete.kt
  buildSrc/jarfilter/src/test/resources/sanitise-stub-constructor/build.gradle
  buildSrc/jarfilter/src/test/resources/sanitise-stub-constructor/kotlin/net/corda/gradle/HasOverloadedConstructorsToStub.kt
  core-deterministic/build.gradle
  serialization-deterministic/build.gradle
Labels: bug

#3571 Add jib gradle plugin to node
  docs/source/building-container-images.rst
  docs/source/index.rst
  node/build.gradle
Labels: enhancement

#3564 CORDA-1744 update jolokia to latest version
  build.gradle
  gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
  gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Labels: Backport

#3588 CORDA-1727 - Document more clearly the supported version of IntelliJ and the IntelliJ Kotlin Plugins. (#3550)
  docs/source/conf.py
  docs/source/getting-set-up.rst
Labels: Backport

#3589 CORDA-1727 - Document more clearly the supported version of IntelliJ and the IntelliJ Kotlin Plugins. (#3550)
  docs/source/conf.py
  docs/source/getting-set-up.rst
Labels: Backport

#3594 Serialization documentation backport
  docs/source/cordapp-custom-serializers.rst
  serialization/src/test/java/net/corda/serialization/internal/amqp/JavaCustomSerializerTests.java
Labels: Backport

#3602 CORDA-1717 - backport bootstrapper to 3.2 (#3496)
  .idea/compiler.xml
  settings.gradle
  tools/network-bootstrapper/build.gradle
  tools/network-bootstrapper/src/main/java/net/corda/bootstrapper/GuiUtils.java
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/Constants.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/NetworkBuilder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/backends/AzureBackend.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/backends/Backend.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/backends/DockerBackend.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/cli/CommandLineInterface.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/cli/CommandParsers.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/InstanceInfo.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/Instantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/azure/AzureInstantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/instance/docker/DockerInstantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/ContainerPusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/azure/AzureContainerPusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/azure/AzureRegistryLocator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/containers/push/docker/DockerContainerPusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/context/Context.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/docker/DockerUtils.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/gui/BootstrapperView.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/gui/Gui.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/BuiltNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/CopiedNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/FoundNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeAdder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeBuilder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeCopier.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeFinder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeInstance.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeInstanceRequest.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodeInstantiator.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/NodePusher.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/nodes/PushedNode.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/notaries/CopiedNotary.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/notaries/NotaryCopier.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/notaries/NotaryFinder.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/serialization/SerializationHelper.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/Volume.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/azure/AzureSmbVolume.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/docker/LocalVolume.kt
  tools/network-bootstrapper/src/main/resources/node-Dockerfile
  tools/network-bootstrapper/src/main/resources/node_info_watcher.sh
  tools/network-bootstrapper/src/main/resources/node_killer.sh
  tools/network-bootstrapper/src/main/resources/notary-Dockerfile
  tools/network-bootstrapper/src/main/resources/rpc-settings.conf
  tools/network-bootstrapper/src/main/resources/run-corda-node.sh
  tools/network-bootstrapper/src/main/resources/run-corda-notary.sh
  tools/network-bootstrapper/src/main/resources/ssh.conf
  tools/network-bootstrapper/src/main/resources/views/bootstrapper.css
  tools/network-bootstrapper/src/main/resources/views/cordalogo.png
  tools/network-bootstrapper/src/main/resources/views/mainPane.fxml
Labels: Backport

#3603 CORDA-1628: Increase max restart count for notary client flows. (#3357)
  node/src/main/resources/reference.conf
Labels: Backport

#3599 CORDA-1588: Add an extra check in the attachment resolution flow to p…
  core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
Labels: Backport

#3604 [CORDA-1634] Destroy child processes when parent exits. (#3368)
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ShutdownManager.kt
Labels: Backport

#3607 Back-ports CORDA-1499 and CORDA-1804
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
  node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
Labels: Backport

#3613 CORDA-1499, CORDA-1804 (#3607)
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
  node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Labels: Backport

#3597 CORDA-1790 Roll back flow transaction on exception
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
Labels: Backport

#3614 CORDA-1812 fix Postgres db bloat issue
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
  node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
Labels: Backport

#3556 CORDA-1748: Delete unwanted default parameter values from Kotlin metadata.
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTransformer.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorDefaultParameterTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionDefaultParameterTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixPackageDefaultParameterTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixPackageTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/PackageWithDefaultParameters.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/asm/ClassMetadata.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/template/PackageWithDefaultParameters.kt
Labels: enhancement

#3562 CORDA-1785: Update JarFilter to delete classes whose outer class is removed.
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/UnwantedCache.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteInnerLambdaTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/FieldRemovalTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/StaticFieldRemovalTest.kt
  buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/UnwantedCacheTest.kt
  buildSrc/jarfilter/src/test/resources/delete-inner-lambda/build.gradle
  buildSrc/jarfilter/src/test/resources/delete-inner-lambda/kotlin/net/corda/gradle/HasInnerLambda.kt
Labels: bug

#3617 Back-port CORDA-1548 Hibernate session not flushed before handing over raw JDBC session to user code (e.g. coin selection)
  finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
Labels: Backport

#3619 Back-port upgrade notes for CORDA-1804
  docs/source/upgrade-notes.rst
Labels: Backport

#3620 CORDA-1814: Remove Quasar's transitive dependencies.
  confidential-identities/build.gradle
  core/build.gradle
Labels: bug

#3616 CORDA-1790 - Roll back flow transaction on exception (#3597)
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
Labels: Backport

#3625 CORDA-1747 fix issue around RPC return of generic objects
  node/src/integration-test/java/net/corda/serialization/reproduction/GenericReturnFailureReproductionIntegrationTest.java
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CollectionSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/MapSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationHelper.kt
  serialization/src/test/java/net/corda/serialization/internal/amqp/JavaGenericsTest.java
Labels: bug

#3586 CORDA-1800: Shrink the Simm Valuation Demo's contract states using ProGuard.
  build.gradle
  constants.properties
  samples/simm-valuation-demo/build.gradle
  samples/simm-valuation-demo/contracts-states/build.gradle
  samples/simm-valuation-demo/flows/build.gradle
Labels: enhancement

#3605 CORDA-1789 - Split Doorman / NM config - fix for CORDA-1510
  node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaCustomSerializerTests.java
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Labels: Backport

#3648 Pre release v3.2 docs
  docs/source/network-builder.rst
  docs/source/release-notes.rst
  docs/source/upgrade-notes.rst
Labels: Release

#3653 CORDA-1674 - Publish Node Explorer artefact (#3437)
  build.gradle
  tools/explorer/capsule/build.gradle
Labels: Backport

#3654 H2 database table upgrade notes from 3.0 to 3.2 fix - related to CORDA-1804.
  docs/source/upgrade-notes.rst
Labels: Backport

#3665 ENT-2296 - Fix typo in docs
  docs/source/tutorial-cordapp.rst
Labels: documentation

#3543 series0ne/corda-demobench-cordapp-select
  tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
Labels: enhancement

#3643 Only build deterministic modules when using JDK8.
  settings.gradle
Labels: bug

#3683 RELEASE - Update upgrade and release notes on master post V3.2
  docs/source/release-notes.rst
  docs/source/upgrade-notes.rst
Labels: Backport, Release, documentation

#3693 Fixes formatting. Fixes link.
  docs/source/blob-inspector.rst
  docs/source/network-bootstrapper.rst
Labels: documentation

#3682 CORDA-1585 - Tidy up participate docs
  docs/source/contributing-index.rst
  docs/source/contributing.rst
  docs/source/index.rst
  docs/source/release-process-index.rst
Labels: Backport

#3718 Backports network bootstrapper docs.
  docs/source/network-bootstrapper.rst
  docs/source/setting-up-a-corda-network.rst
  docs/source/tools-index.rst
Labels: Backport

#3719 Backports network bootstrapper docs. (#3718)
  docs/source/network-bootstrapper.rst
  docs/source/setting-up-a-corda-network.rst
  docs/source/tools-index.rst
Labels: Backport, documentation

#3729 CORDA-1861: Remove default value to make createUnstartedNode() unambiguous.
  testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt
Labels: bug
