Repository corda/corda, pull requests merged in 2018-05, with the labels that each got.

#3035 CORDA-1304 Remove superfluous registerInitiatedFlow calls from tutorial and exam…
  core/src/test/java/net/corda/core/flows/FlowsInJavaTest.java
  core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
  core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt
  docs/source/api-testing.rst
  docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/mocknetwork/TutorialMockNetwork.kt
  docs/source/flow-testing.rst
  samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
Labels: Backport

#3034 Update jolokia to 1.5.0 (#2617)
  docs/source/changelog.rst
  node/src/main/resources/build.properties
Labels: Backport

#3044 CORDA-1389: Delete the root nodes directory before initialising the nodes
  constants.properties
  gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
Labels: Backport

#3030 CORDA-1403 - Generics serialization issue
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
Labels: bug

#3051 CORDA-1229 - Fix issue with setter-based serialisation
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/SetterConstructorTests.java
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
Labels: Backport

#3055 Fixed invalid page ref in upgrade-notes.rst
  docs/source/upgrade-notes.rst
Labels: Backport

#3056 CORDA-847 - RPC Server lib refactoring
  docs/source/changelog.rst
  node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/X509UtilitiesTest.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoTests.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/serialization/kryo/KryoServerSerializationScheme.kt
  node/src/main/kotlin/net/corda/node/serialization/kryo/RpcServerObservableSerializer.kt
  node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt
Labels: refactor

#3076 CORDA-1001 - Remove peristent map in NodeSchedulerService (#763)
  docs/source/changelog.rst
  node/src/integration-test/kotlin/net/corda/node/services/events/ScheduledFlowIntegrationTests.kt
  node/src/integration-test/kotlin/net/corda/testMessage/ScheduledState.kt
  node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
  node/src/main/kotlin/net/corda/node/services/events/PersistentScheduledFlowRepository.kt
  node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
  node/src/test/kotlin/net/corda/node/services/events/PersistentScheduledFlowRepositoryTest.kt
Labels: Backport

#3095 CORDA-1403 - Generics serialization issue (#3030)
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
Labels: Backport

#3068 CORDA-1385: Ignore duplicate packages and sub-packages in driver extraCordappPackagesToScan
  node/src/integration-test/kotlin/net/corda/node/CordappScanningDriverTest.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt
  node/src/test/kotlin/net/corda/node/internal/cordapp/CordappLoaderTest.kt
Labels: Backport

#3098 CORDA-1414 - node should continue with parameters from file when network map not available
  node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
Labels: Backport

#3142 Remove duplicate Netty classes from Node.
  build.gradle
  node-api/build.gradle
  node/build.gradle
Labels: bug

#3096 CORDA-1344 - Fix query paging in scheduled flow tests (#2970)
  docs/source/api-vault-query.rst
  node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
  node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
  node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Labels: Backport

#3106 CORDA-1466: Fix publication of PDF developer documentation
  docs/make-docsite.sh
Labels: Backport

#3178 Fix build breakage with Gradle 4.7.
  tools/demobench/build.gradle
Labels: bug

#3114 CORDA-1317 - Add cert role to CSR and doorman issue cert according to the cert role
  node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/config/ConfigParsingTest.kt
  node/src/main/kotlin/net/corda/node/ArgsParser.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
  node/src/test/kotlin/net/corda/node/ArgsParserTest.kt
  node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: Backport

#3189 [CORDA-1397]: Fixed incorrect exception handling in `NodeVaultService…
  docs/source/changelog.rst
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Labels: Backport

#3191 CORDA-1386 - Updates withoutIssuer to not strip display token size.
  core/src/main/kotlin/net/corda/core/contracts/Structures.kt
Labels: Backport

#3197 [CORDA-1342]: The shell doesn't print the return value of a started f…
  node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
Labels: Backport

#3195 [CORDA-1455]: Error in process-id deletion process allows multiple in…
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Labels: Backport

#2865 CORDA-1405: Integration test for network parameter updates and improved logging
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
  node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
  node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
Labels: Backport

#3214 Move RxNotification serializer into the serialization module
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt
  node/src/main/kotlin/net/corda/node/serialization/amqp/AMQPServerSerializationScheme.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/custom/RxNotificationSerializer.kt
Labels: bug

#3210 Using a List for the identity certs in InMemoryIdentityService and PersistentIdentityService
  CONTRIBUTORS.md
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
  node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
  node/src/test/kotlin/net/corda/node/services/identity/InMemoryIdentityServiceTests.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
  tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
Labels: contribution

#3205 Backports/corda 1338 corda 1394
  core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
  docs/source/changelog.rst
  finance/src/test/kotlin/net/corda/finance/contracts/asset/DummyFungibleContract.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV2.kt
  finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV2.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
  node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
  node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Labels: Backport

#3232 CORDA-1530 - Generics break default evolver
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializer.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EvolvabilityTests.kt
  serialization/src/test/resources/net/corda/serialization/internal/amqp/EvolvabilityTests.addMandatoryFieldWithAltConstructorForceReorder
  serialization/src/test/resources/net/corda/serialization/internal/amqp/EvolvabilityTests.moreComplexNonNullWithReorder
Labels: bug

#3213 CORDA-1521 - Fix rpc attachment smoke test / better AMQP logging
  client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/Schema.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/custom/InputStreamSerializer.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/StreamTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/testutils/AMQPTestUtils.kt
Labels: bug

#3245 Resolve compiler warnings for Kotlin >= 1.2.40.
  finance/src/main/kotlin/net/corda/finance/flows/CashExitFlow.kt
  finance/src/main/kotlin/net/corda/finance/flows/CashIssueFlow.kt
  finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt
Labels: trivial

#3253 Serializer backports
  .ci/api-current.txt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/ArraySerializer.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeSimpleTypesTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.addMandatoryFieldWithAltConstructorForceReorder
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.moreComplexNonNullWithReorder
Labels: Backport

#3255 CORDA-866, ENT-1933 backport
  core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
  docs/source/network-map.rst
  docs/source/serialization-default-evolution.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
  node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
  node/src/test/resources/network-compatibility/network-parameters
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
  testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
Labels: Backport
