Repository corda/corda, pull requests merged in 2018-08, with the labels that each got.

#3731 CORDA-1862: Allow MockNetwork to create StartedMockNode from UnstartedMockNode.
  testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt
  testing/node-driver/src/test/kotlin/net/corda/testing/node/MockNetworkTest.kt
Labels: enhancement

#3700 CORDA-1848 Add example alias and autocomplete for CLI tools
  tools/bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt
Labels: enhancement

#3739 Jmx Reporter Addition to allow for New Relic over Jolokia alternative
  docs/source/corda-configuration-file.rst
  node/build.gradle
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/main/resources/reference.conf
  node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
  node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
Labels: contribution, enhancement

#3765 NOTICK - Fix version reference for New Relic dependency
  build.gradle
  constants.properties
  node/build.gradle
Labels: trivial

#3783 Config file and base dir can be specified together
  node/src/main/kotlin/net/corda/node/NodeArgsParser.kt
  node/src/test/kotlin/net/corda/node/NodeArgsParserTest.kt
Labels: enhancement

#3784 Include the deterministic test-data.jar in the build's assembly.
  core-deterministic/testing/data/build.gradle
Labels: trivial

#3792 [CORDA-1681]: It is not possible to run stateMachinesSnapshot from the shell (fixed).
  core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
Labels: Backport

#3788 CORDA-1895 Fix loadStates for large page sizes and added unit test.
  docs/source/changelog.rst
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
  node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Labels: Backport

#3794 CORDA-1906: Add Servlet 3.x implementation into the WebServer.
  webserver/build.gradle
Labels: bug

#3811 Fix Jib build
  node/build.gradle
Labels: bug

#3819 CORDA-1905: Extend JSON deserialisation to handle Amount<T> for any T
  client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt
  client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt
  client/jackson/src/test/kotlin/net/corda/client/jackson/AmountTest.kt
  client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
  samples/irs-demo/build.gradle
  samples/irs-demo/web/build.gradle
  samples/network-visualiser/build.gradle
Labels: Backport

#3820 CORDA-1906: Add Servlet 3.1 implementation into the WebServer. (#3794)
  webserver/build.gradle
Labels: Backport

#3835 Ensure that every CheatingSecurityProvider has a unique name.
  core-deterministic/testing/src/test/kotlin/net/corda/deterministic/CheatingSecurityProvider.kt
Labels: bug

#3827 CORDA-1907: Allow Corda's shell to deserialise using generic type information.
  .ci/api-current.txt
  client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt
  client/jackson/src/test/kotlin/net/corda/client/jackson/StringToMethodCallParserTest.kt
  node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
  node/src/test/kotlin/net/corda/node/InteractiveShellTest.kt
Labels: Backport

#3859 CORDA-1945: properly support double-width interp stack slots in superclasses when synthesising
  serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenter.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenterTest.kt
Labels: bug

#3857 CORDA-1812 - fix Postgres db bloat issue (#3614)
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
  node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
  node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
Labels: Backport

#3867 [CORDA-1841]: Made paths in tutorial-cordapp consistent. (#3778)
  docs/source/tutorial-cordapp.rst
Labels: Backport

#3869 CORDA-1888 Fix Vault Query composite queries (#3775)
  node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
  node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
  node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
  node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyState.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/VaultFiller.kt
Labels: Backport

#3380 DEVOPS-764 - Jolokia dependency is incorrectly specified and removed in master
  webserver/build.gradle
  webserver/src/main/kotlin/net/corda/webserver/JolokiaSlf4Adapter.kt
Labels: Backport
