Repository corda/corda, pull requests merged in 2019-01, with the labels that each got.

#4570 CORDA-2418: Fixed inability to use TestCordapp under gradle in Window…
  core/src/main/kotlin/net/corda/core/internal/PathUtils.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
Labels: Backport

#4574 CORDA-2209 backport of individual ACK on the AMQP bridge
  node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
Labels: Backport

#4589 CORDA-2442: Added wither methods to the vault query classes
  core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
Labels: Backport

#4594 [CORDA-2441] Fix Stdout progress renderer to swap out correct appender (#4582)
  tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
Labels: Backport

#4578 CORDA-2434: CordaRPCClient now only has c'tors rather a mix of c'tors…
  .ci/api-current.txt
  client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/CordaRPCClientUtils.kt
  docs/source/clientrpc.rst
  node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcSslTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
  webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
Labels: Backport

#4597 [CORDA-2432] Update documentation for filtering by state relevancy in vault queries
  docs/source/api-vault-query.rst
  docs/source/app-upgrade-notes.rst
  docs/source/changelog.rst
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
  node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
  node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/VaultFiller.kt
Labels: Backport

#4613 Fix issue with devModeOptions.allowCompatabilityZone not working
  node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
Labels: bug

#4622 CORDA-2475 Adjust attachments query logic to return correct results …
  core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
  core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderStaticContractTests.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
  node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
Labels: Backport

#4619 [CORDA-2435] Print an error and exit if the vault contains V3 states
  docs/source/app-upgrade-notes.rst
  docs/source/release-notes.rst
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/api/VaultServiceInternal.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
  node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
  node/src/main/resources/reference.conf
  node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Labels: Backport

#4616 CORDA-2482: Fix issue with devModeOptions.allowCompatibilityZone not working (#4613)
  node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
Labels: Backport

#4615 CORDA-2445 print out the underlying error when an RPC call fails
  tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
Labels: Backport

#4625 CORDA-2485 Add minimum platform version check before attempting a hash -> signat…
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
Labels: Backport

#4629 CORDA-2490 Attachment in the directory fails to correctly upload (#4627)
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
Labels: Backport

#4626 CORDA-2228: Exceptions emanating from ReceiveFinalityFlow are sent to…
  core/src/test/kotlin/net/corda/core/flows/ReceiveFinalityFlowTest.kt
  node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt
Labels: Backport

#4633 CORDA-2504 improve error message of missing contract attachments (#4628)
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
  docs/source/api-contract-constraints.rst
  docs/source/api-testing.rst
Labels: Backport

#4599 ENT-2822: Add a note about experimental notary upgradability
  docs/source/changelog.rst
Labels: Backport

#4646 CORDA-2510: Added missing confidential-identities CorDapp to DemoBench (#4636)
  tools/demobench/build.gradle
  tools/demobench/src/main/kotlin/net/corda/demobench/plugin/CordappController.kt
Labels: Backport

#4656 [CORDA-2516] Add missing database tables to documentation (#4651)
  docs/source/node-database.rst
Labels: Backport

#4658 [Backport] - Improve documentation surrounding network parameter updates/flag day
  docs/source/network-map.rst
Labels: Backport

#4662 CORDA-2419 - JavaFX requirement for Node Explorer
  docs/source/node-explorer.rst
Labels: Backport, docs

#4666 CORDA-2524: Minor – reduce notary service logging noise
  node/src/main/kotlin/net/corda/node/services/transactions/SimpleNotaryService.kt
Labels: bug

#4675 Minor docs fix for IRS Demo
  samples/irs-demo/README.md
Labels: docs

#4672 CORDA-2524: Minor – reduce notary service logging noise
  node/src/main/kotlin/net/corda/node/services/transactions/SimpleNotaryService.kt
Labels: Backport, bug

#4679 ENT-2822: Update notary configuration docs
  docs/source/corda-configuration-file.rst
Labels: bug, docs

#4684 ENT-2822: Update notary configuration docs
  docs/source/corda-configuration-file.rst
Labels: Backport, docs

#4678 ENT-2967 Fix up use of various JDK performance contention points (#4608)
  core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
  core/src/main/kotlin/net/corda/core/crypto/SignatureScheme.kt
  core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt
Labels: Backport

#4686 CORDA-2531 - State mappings are now also updated for new reference states. (#4681)
  core/src/test/kotlin/net/corda/core/flows/ReferencedStatesFlowTests.kt
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Labels: Backport

#4682 CORDA-2520 Cherry pick
  core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
  core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
  core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
  core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
  core/src/main/kotlin/net/corda/core/internal/NetworkParametersServiceInternal.kt
  core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
  core/src/test/kotlin/net/corda/core/internal/NetworkParametersResolutionTest.kt
  core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt
  node/src/main/kotlin/net/corda/node/internal/DBNetworkParametersStorage.kt
  node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
  node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockNetworkParametersService.kt
Labels: Backport

#4692 Tighten no overlap check. (#4690)
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt
Labels: Backport

#4689 CORDA-2515 Fix bug in verifier for has to signature constraints (auto-migration)
  core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
Labels: Backport

#4660 [CORDA-2518] - Refresh the current API file
  .ci/api-current.txt
Labels: Backport

#4677 correct command docs for clear network map cache
  docs/source/network-map.rst
Labels: docs
