Repository corda/corda, pull requests merged in 2019-09, with the labels that each got.

#5438 Update dockerform task steps
  docs/source/generating-a-node.rst
Labels: docs

#5386 CORDA-3018 Whitelisting attachments by public key - phase two tooling
  core-tests/src/test/kotlin/net/corda/coretests/transactions/AttachmentsClassLoaderSerializationTests.kt
  core-tests/src/test/kotlin/net/corda/coretests/transactions/AttachmentsClassLoaderTests.kt
  core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt
  core/src/main/kotlin/net/corda/core/internal/AttachmentTrustCalculator.kt
  core/src/main/kotlin/net/corda/core/internal/ServiceHubCoreInternal.kt
  core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt
  core/src/main/kotlin/net/corda/core/internal/messaging/InternalCordaRPCOps.kt
  core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
  core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
  core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
  docs/source/api-contract-constraints.rst
  docs/source/changelog.rst
  docs/source/checkpoint-tooling.rst
  docs/source/corda-configuration-file.rst
  docs/source/node-administration.rst
  docs/source/upgrading-cordapps.rst
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
  node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
  node/src/main/kotlin/net/corda/node/migration/MigrationNamedCacheFactory.kt
  node/src/main/kotlin/net/corda/node/migration/MigrationServicesForResolution.kt
  node/src/main/kotlin/net/corda/node/services/attachments/NodeAttachmentTrustCalculator.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
  node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt
  node/src/main/kotlin/net/corda/node/services/persistence/AttachmentStorageInternal.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
  node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
  node/src/test/kotlin/net/corda/node/services/attachments/AttachmentTrustCalculatorTest.kt
  node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/CordaClassResolverTests.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/services/InternalMockAttachmentStorage.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
  tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt
  tools/shell/src/main/java/net/corda/tools/shell/AttachmentShellCommand.java
  tools/shell/src/main/java/net/corda/tools/shell/CheckpointShellCommand.java
  tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java
  tools/shell/src/main/kotlin/net/corda/tools/shell/AttachmentTrustTable.kt
  tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
Labels: enhancement

#5469 CORDA-3218: Make set of serializer types considered suitable for object reference to be configurable.
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationHelper.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationOutput.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt
Labels: enhancement

#5483 ENT-4198 Adding legal text
  docs/source/index.rst
  docs/source/legal-info.rst
Labels: docs

#5511 CORDA-2050: Do not add java.lang.Class fields and properties to local type cache.
  docs/source/example-code/build.gradle
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ArraySerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
Labels: bug

#5512 CORDA-2050: Ensure that ArraySerializer.elementType is resolved for GenericArray.
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ArraySerializer.kt
Labels: bug

#5406 Fix typo in docs/quickstart
  docs/source/quickstart-build.rst
Labels: docs

#5506 ENT-4104: Removing metrics we don't use.
  docs/source/design/monitoring-management/design.md
Labels: docs

#5522 CORDA-3273: Restore deprecated use of Class.newInstance() for sake of DJVM.
  core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
Labels: bug

#5525 Merge of 4.3 -> 4.4
  build.gradle
  client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCMultipleInterfacesTests.kt
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
  constants.properties
  detekt-baseline.xml
  docs/source/aws-vm.rst
  docs/source/azure-vm.rst
  docs/source/changelog.rst
  docs/source/clientrpc.rst
  docs/source/cordapp-build-systems.rst
  docs/source/demobench.rst
  docs/source/deploying-a-node.rst
  docs/source/design/monitoring-management/design.md
  docs/source/example-code/build.gradle
  docs/source/quickstart-build.rst
  node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
  node/src/main/kotlin/net/corda/node/services/config/schema/v1/ConfigSections.kt
  node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt
  node/src/main/kotlin/net/corda/node/services/rpc/RPCServer.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
  samples/attachment-demo/build.gradle
  samples/bank-of-corda-demo/build.gradle
  samples/cordapp-configuration/build.gradle
  samples/notary-demo/build.gradle
  samples/simm-valuation-demo/build.gradle
  settings.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
  testing/testserver/build.gradle
  testing/testserver/src/integration-test/kotlin/net/corda/webserver/WebserverDriverTests.kt
  testing/testserver/src/main/java/CordaWebserverCaplet.java
  testing/testserver/src/main/kotlin/net/corda/webserver/WebArgsParser.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/WebServer.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/WebServerConfig.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/api/APIServer.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/api/Query.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/converters/Converters.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/internal/APIServerImpl.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/internal/AllExceptionMapper.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/services/WebServerPluginRegistry.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/servlets/AttachmentDownloadServlet.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/servlets/CorDappInfoServlet.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/servlets/DataUploadServlet.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/servlets/ObjectMapperConfig.kt
  testing/testserver/src/main/kotlin/net/corda/webserver/servlets/ResponseFilter.kt
  testing/testserver/src/main/resources/web-reference.conf
  testing/testserver/testcapsule/build.gradle
  tools/demobench/build.gradle
  tools/demobench/src/main/kotlin/net/corda/demobench/web/WebServerController.kt
Labels: Upstream Merge

#5516 CORDA-3124: Ensure transaction is fully verified before sending to no…
  core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
  core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
  docs/source/changelog.rst
  node/src/test/kotlin/net/corda/node/services/transactions/NotaryWhitelistTests.kt
  node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
Labels: bug
