Repository corda/corda, pull requests merged in 2019-11, with the labels that each got.

#5568 adding one point to whitelist contract constraints migration - signed…
  docs/source/cordapp-constraint-migration.rst
Labels: docs

#5657 CORDA-3392: Fix caching of local AMQPSerializer<*> instances.
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt
Labels: bug

#5676 CORDA-2876: Ensure NodeConfig does not have devModeOptions outside of devMode,
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: bug

#5671 NOTICK - Fixes for advanced concepts docs
  docs/source/cordapp-advanced-concepts.rst
Labels: docs

#5678 CORDA-2876: Add explicit Kotlin dependencies to DJVM serialization modules.
  constants.properties
  core-deterministic/build.gradle
  core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt
  serialization-djvm/build.gradle
  serialization-djvm/deserializers/build.gradle
Labels: trivial

#5684 [CORDA-3298] - Update sql server driver version
  docs/source/node-database.rst
Labels: docs

#5685 ENT-4107: Document blob inspector issue
  docs/source/blob-inspector.rst
Labels: docs

#5679 CORDA-3393 Lazy load `MessageDeduplicationHandler.flowId`
  node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
Labels: enhancement

#5689 NOTICK - Fix typo in node services docs
  docs/source/node-services.rst
Labels: docs

#5687 CORDA-3406: Modify DemoBench to make using the DJVM obvious and optional.
  build.gradle
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeData.kt
  tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
  tools/demobench/src/main/resources/net/corda/demobench/style.css
  tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
  tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
Labels: enhancement

#5532 CORDA-3181 Correct JDK install instructions + streamlining
  docs/source/cordapp-build-systems.rst
  docs/source/getting-set-up.rst
Labels: docs

#5699 CORDA-3407: Install external byte-code cache for sandboxed CorDapps.
  constants.properties
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicContractCryptoTest.kt
  node/src/integration-test/kotlin/net/corda/node/services/NonDeterministicContractVerifyTest.kt
  node/src/integration-test/kotlin/net/corda/node/services/SandboxAttachmentsTest.kt
  node/src/main/kotlin/net/corda/node/internal/djvm/DeterministicVerifier.kt
  node/src/main/kotlin/net/corda/node/services/transactions/DeterministicVerifierFactoryService.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestBase.kt
Labels: enhancement

#5711 CORDA-3414: Upgrade to Corda Gradle plugins 5.0.6.
  .ci/api-current.txt
  buildSrc/build.gradle
  constants.properties
Labels: enhancement

#5720 CORDA-2876: Fix serialization-djvm module for Java 11.
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeCertificatesTest.kt
Labels: bug

#5727 CORDA-2876: Upgrade DJVM to 1.0-RC03.
  constants.properties
  node/src/main/kotlin/net/corda/node/internal/djvm/DeterministicVerifier.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestBase.kt
Labels: enhancement

#5730 CORDA-2963: Add calendars.properties to deterministic-rt.jar.
  create-jdk8u/Makefile
  create-jdk8u/build.gradle
Labels: enhancement

#5733 CORDA-2963: Migrate deterministic-rt.jar into DJVM repository.
  create-jdk8u/.gitignore
  create-jdk8u/Makefile
  create-jdk8u/build.gradle
  create-jdk8u/settings.gradle
Labels: trivial

#5738 CORDA-2876: Upgrade to deterministic-rt 1.0-RC01.
  build.gradle
  constants.properties
  jdk8u-deterministic/build.gradle
  node/build.gradle
Labels: enhancement

#5748 [CORDA-3373][CORDA-3374] Update Cordform docs to discuss setting Jolokia version, update version number
  docs/source/generating-a-node.rst
  docs/source/node-administration.rst
Labels: docs

#5740 [CORDA-3442] Update app upgrade notes for gradle version for PV5
  docs/source/app-upgrade-notes.rst
Labels: docs

#5281 CORDA-3015: Add StatePointer classes to corda-core-deterministic. (#5227)
  core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
Labels: Backport, bug

#5749 Fix typo "transcation" => "transaction"
  docs/source/cordapp-advanced-concepts.rst
Labels: bug, docs, trivial

#5660 CORDA-3197 Fix flow has been waiting message
  detekt-baseline.xml
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/rpc/CheckpointDumper.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineState.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
Labels: enhancement
