Repository corda/corda, pull requests merged in 2019-03, with the labels that each got.

#4826 [CORDA-2687] Ensure collections of unknown types are not carpented
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/StaticInitialisationOfSerializedObjectTest.kt
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/StaticInitialisationOfSerializedObjectTest.unknownCollection
Labels: Backport

#4827 CORDA-2679: Allow more Network Bootstrapper code to be unloaded from JVM.
  node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapperTest.kt
Labels: bug

#4846 CORDA-2697: Upgrade to Corda Gradle plugins 4.0.41.
  constants.properties
Labels: bug, enhancement

#4849 CORDA-2688 - Add Serialization Context option for no carpenting
  core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/SerializationScheme.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ObjectSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/RemoteSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeLoader.kt
  serialization/src/test/java/net/corda/serialization/internal/carpenter/JavaCalculatedValuesToClassCarpenterTest.java
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeNeedingCarpentryTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeSimpleTypesTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenterTestUtils.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/CompositeMemberCompositeSchemaToClassCarpenterTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/InheritanceSchemaToClassCarpenterTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/MultiMemberCompositeSchemaToClassCarpenterTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/model/ClassCarpentingTypeLoaderTests.kt
Labels: enhancement

#4842 CORDA-2694: Prevent Node Explorer from crashing should it receive unknown transaction objects.
  client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
  client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt
  core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt
  core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
  core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
  core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
  core/src/test/kotlin/net/corda/core/utilities/LazyMappedListTest.kt
Labels: bug

#4855 CORDA-2642, CORDA-2699: Upgrade to Corda Gradle plugins 4.0.42 to remove Jolokia from sample CorDapps.
  constants.properties
Labels: bug

#4837 CORDA-2684 Added new guide on CorDapp Constraints Migration procedures.
  docs/source/api-contract-constraints.rst
  docs/source/app-upgrade-notes.rst
  docs/source/cordapp-constraint-migration.rst
  docs/source/cordapp-upgradeability.rst
  docs/source/network-bootstrapper.rst
  docs/source/upgrading-cordapps.rst
Labels: docs

#4861 CORDA-2569: Add "flow kill <ID>" command to Corda's shell.
  client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt
  client/jackson/src/test/kotlin/net/corda/client/jackson/StateMachineRunIdTest.kt
  client/rpc/src/smoke-test/java/net/corda/java/rpc/StandaloneCordaRPCJavaClientTest.java
  client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
  core/src/smoke-test/kotlin/net/corda/core/NodeVersioningTest.kt
  core/src/smoke-test/kotlin/net/corda/core/cordapp/CordappSmokeTest.kt
  docs/source/shell.rst
  node/src/main/kotlin/net/corda/node/internal/rpc/proxies/AuthenticatedRpcOpsProxy.kt
  node/src/main/kotlin/net/corda/node/internal/security/RPCSecurityManagerImpl.kt
  node/src/test/kotlin/net/corda/node/services/RPCSecurityManagerTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt
  tools/shell/build.gradle
  tools/shell/src/main/java/net/corda/tools/shell/FlowShellCommand.java
  tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java
  tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
  tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
Labels: bug, enhancement

#4852 CORDA-2703: Fix use of commas in node.conf examples.
  docs/source/clientrpc.rst
Labels: docs

#4867 CORDA-2725: Fix logging configuration for DJVM CLI.
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CommandBase.kt
  djvm/cli/src/main/resources/log4j2.xml
  djvm/src/main/kotlin/net/corda/djvm/messages/Severity.kt
Labels: bug

#4865 CORDA-2721: Update `djvm check` documentation, and fix CLI tool installation.
  constants.properties
  djvm/shell/djvm
  djvm/shell/install
  docs/source/key-concepts-djvm.rst
Labels: bug

#4868 CORDA-2725: Include DEBUG in DJVM CLI help's list of logging levels.
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CommandBase.kt
Labels: bug, trivial

#4873 CORDA-2729: Update integration testing instructions to explicitly mention node-driver dependency
  docs/source/tutorial-integration-testing.rst
Labels: docs

#4866 CORDA-2704 - Allow Evolver to ignore carpentry errors
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializer.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializers.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/UncarpentableSerializer.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MetaCarpenter.kt
  node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/SetterConstructorTests.java
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/CarpentryAndEvolverTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentrySimpleTypesTest.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/testutils/TerribleCarpenter.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/CompositeMemberCompositeSchemaToClassCarpenterTests.kt
  node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/InheritanceSchemaToClassCarpenterTests.kt
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/CarpentryAndEvolverTests.disabledByEnv
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/CarpentryAndEvolverTests.ensureTopLevelCarpentryStillErrorsOnFailure
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/CarpentryAndEvolverTests.failstoCarpentFirstSortedElementIsGeneric
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/CarpentryAndEvolverTests.ignoresSeveralErrors
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/CarpentryAndEvolverTests.newTypeWeCantCarpentIsIgnoredWhenRemovedByEvolver
  node-api/src/test/resources/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.removesList
Labels: bug

#4874 NOKEY: Apply Docker Remote API plugin using Gradle's plugins block.
  docker/build.gradle
Labels: trivial

#4883 RELEASE - Add password reset, cope with all git tickets marked in Jira
  release-tools/jiraReleaseChecker.py
Labels: Release

#4881 CORDA-2629: Configure smoke-test nodes to have validating notaries.
  testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt
Labels: bug

#4877 CORDA-2728: Add Quasar lib update step to applicataion upgrade notes
  docs/README.md
  docs/source/app-upgrade-notes.rst
  docs/source/tutorial-cordapp.rst
Labels: docs

#4870 CORDA-2741 RPC client connection management section not fully working
  docs/source/clientrpc.rst
  samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/IssueCash.kt
  samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
Labels: docs

#4882 [CORDA-2737] Buffer events from observables in ProgressTracker until subscribed to
  core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
  core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt
  finance/workflows/src/main/kotlin/net/corda/finance/flows/CashIssueAndPaymentFlow.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
  tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
Labels: bug

#4884 Release v3.4 release notes
  docs/source/_static/versions
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/release-notes.rst
  docs/source/upgrade-notes.rst
Labels: Release, docs

#4891 CORDA-2393 Improve documentation for PostgreSQL to avoid missing hibernate_sequence
  docs/source/node-database.rst
Labels: docs

#4893 CORDA-2747: Package DJVM CLI for delivery.
  build.gradle
  djvm/build.gradle
  djvm/cli/build.gradle
  djvm/cli/src/shell/djvm
  djvm/cli/src/shell/djvm.bat
  djvm/cli/src/shell/install
Labels: enhancement

#4898 CORDA-2757 / ENT-3060 - Change log level in flow transition executor
  node/src/main/kotlin/net/corda/node/services/statemachine/TransitionExecutorImpl.kt
Labels: enhancement

#4896 CORDA-2748 Always set the ThreadLocal in the Fiber from the Thread, even if not yet set in the Thread.
  node/src/main/kotlin/net/corda/node/services/statemachine/FiberUtils.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
Labels: bug

#4894 [CORDA-2738] Allow the ProgressTracker to cope with child trackers with the same steps
  core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
  core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt
  finance/workflows/src/main/kotlin/net/corda/finance/flows/CashIssueAndPaymentFlow.kt
  tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
  tools/shell/src/test/kotlin/net/corda/tools/shell/utilities/ANSIProgressRendererTest.kt
Labels: bug

#4899 CORDA-2759: Use GlobalTestPortAllocation for Node's integration tests.
  node/build.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/GlobalTestPortAllocation.kt
Labels: bug

#4902 BUILD: Fix some warnings about @BelongsToContract in tests.
  core/src/test/kotlin/net/corda/core/internal/TopologicalSortTest.kt
  core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt
  node/src/integration-test/kotlin/net/corda/testMessage/ScheduledState.kt
  node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
  node/src/test/kotlin/net/corda/node/services/transactions/ResolveStatePointersTest.kt
  node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt
  node/src/test/kotlin/net/corda/node/testing/MessageChainState.kt
Labels: trivial

#4906 CORDA-2763 - Log censored config at startup
  node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt
Labels: enhancement

#4907 CORDA-2653 - during initialisation a Corda Service should have a thread context classloader
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
Labels: bug

#4911 CORDA-2750: Fix published names for DJVM artifacts.
  djvm/djvm/build.gradle
  djvm/djvm/cli/build.gradle
Labels: bug

#4913 CORDA-2775: Simplify SourceClassLoader logic for DJVM.
  djvm/djvm/build.gradle
  djvm/djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
  djvm/djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt
  djvm/djvm/src/main/kotlin/net/corda/djvm/rewiring/ClassRewriter.kt
  djvm/djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
  djvm/djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt
  djvm/djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
  djvm/djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java
  djvm/djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
  djvm/djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Labels: enhancement

#4918 CORDA-2779 - Fix Netmap REST endpoint docs
  docs/source/network-map.rst
Labels: docs

#4921 BUILD: Use global port allocator for flaky HardRestartTest.
  node/src/integration-test/kotlin/net/corda/node/services/statemachine/HardRestartTest.kt
Labels: bug

#4927 corda-2781 replace manual versions with substitutions
  docs/source/api-scanner.rst
  docs/source/api-testing.rst
  docs/source/app-upgrade-notes.rst
  docs/source/azure-vm.rst
  docs/source/cli-application-shell-extensions.rst
  docs/source/conf.py
  docs/source/cordapp-build-systems.rst
  docs/source/deploying-a-node.rst
  docs/source/generating-a-node.rst
  docs/source/network-bootstrapper.rst
  docs/source/running-a-notary.rst
  docs/source/testnet-explorer-corda.rst
  docs/source/tutorial-cordapp.rst
  docs/source/writing-a-cordapp.rst
Labels: docs

#4926 CORDA-2786: Certificates directory is only required for node startup
  node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Labels: bug

#4928 CORDA-2783 - Improve error message for initial registration with devMode=true
  node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
Labels: enhancement

#4934 Fix incorrect version identifiers in URL's by adopting |corda_version| consistently.
  docs/source/generating-a-node.rst
  docs/source/network-bootstrapper.rst
  docs/source/testnet-explorer-corda.rst
  docs/source/tutorial-cordapp.rst
Labels: docs

#4936 CORDA-2804: Replace JPA 2.1 annotations with JPA 2.2.
  core-deterministic/build.gradle
  core/build.gradle
Labels: bug

#4886 RELEASE - Fix DemoBench Windows installer (#3451)
  tools/demobench/package-demobench-exe.bat
  tools/demobench/package/bugfixes/apply.bat
Labels: Backport

#4947 CORDA-2808 docs build page
  docs/source/building-the-docs.rst
Labels: docs

#4956 CORDA-2809 - reduce latex/pdf erros
  docs/make-docsite.sh
Labels: docs

#4963 (BACKPORT) ENT-3121 restrict custom serializers
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/concurrent/CordaFuture.kt
  core/src/main/kotlin/net/corda/core/contracts/ContractAttachment.kt
  core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
  core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
  core/src/main/kotlin/net/corda/core/crypto/NullKeys.kt
  core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
  core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
  core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
  core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
  node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationService.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistryTests.kt
Labels: Backport
