Repository corda/corda, pull requests merged in 2019-10, with the labels that each got.

#5535 CORDA-2050: Remove Gradle's evaluation dependency on node:capsule.
  core/build.gradle
Labels: bug

#5589 CORDA-3318: fixed config property names in docs
  docs/source/network-map.rst
Labels: docs

#5596 [ENT-4119] Make welcome message more accurate
  tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
  tools/shell/src/main/resources/net/corda/tools/shell/base/login.groovy
Labels: bug

#5612 [CORDA-3342] - Show proper error message and adjust indentation in shell
  tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
Labels: bug

#5620 CORDA-3346: Remove the JitPack repository from Corda.
  build.gradle
  samples/irs-demo/build.gradle
Labels: bug

#5619 CORDA-3346: Replace JitPack dependency on JediTerm with 2.22 from Maven Central.
  tools/demobench/build.gradle
  tools/demobench/libs/linux/x86/libpty.so
  tools/demobench/libs/linux/x86_64/libpty.so
  tools/demobench/libs/macosx/x86/libpty.dylib
  tools/demobench/libs/macosx/x86_64/libpty.dylib
  tools/demobench/libs/pty4j-0.7.2.jar
  tools/demobench/libs/purejavacomm-0.0.18.jar
  tools/demobench/libs/terminal-331a005d6793e52cefc9e2cec6774e62d5a546b1.jar
  tools/demobench/libs/win/x86/libwinpty.dll
  tools/demobench/libs/win/x86/winpty-agent.exe
  tools/demobench/libs/win/x86/winpty.dll
  tools/demobench/libs/win/x86_64/cyglaunch.exe
  tools/demobench/libs/win/x86_64/winpty-agent.exe
  tools/demobench/libs/win/x86_64/winpty.dll
  tools/demobench/libs/win/xp/winpty-agent.exe
  tools/demobench/libs/win/xp/winpty.dll
Labels: bug

#5637 CORDA-2963: Update the Deterministic Java API artifacts.
  create-jdk8u/Makefile
  create-jdk8u/build.gradle
Labels: enhancement

#5645 CORDA-3327: Fix API scanning for Java 11.
  build.gradle
  constants.properties
  core-tests/build.gradle
Labels: bug

#5650 CORDA-3388: Restore mapping of 'java.lang.Void -> void'
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt
Labels: bug
