Repository corda/corda, pull requests merged in 2019-05, with the labels that each got.

#5062 CORDA-2847: Support custom serialisers when attaching missing attachm…
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
  samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/plugin/customserializers/UnusedFinanceSerializers.kt
Labels: Backport

#5074 Backport CORDA-2477
  core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
  core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt
  docs/source/api-contract-constraints.rst
  docs/source/app-upgrade-notes.rst
  docs/source/versioning.rst
  testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
Labels: Backport

#5079 Add documentation on Corda Services / Service classes
  docs/source/api-service-classes.rst
  docs/source/corda-api.rst
Labels: docs

#5088 CORDA-825 Test jdbc session and entity manager in corda service constuctors
  node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
Labels: bug

#5096 BACKPORT Add documentation on Corda Services / Service classes
  docs/source/api-service-classes.rst
  docs/source/corda-api.rst
Labels: Backport, docs

#5021 CORDA-2817 Changelog for bug fix to stop commands being combined.
  docs/source/changelog.rst
Labels: docs

#5104 CORDA-2892 Add a `TransactionBuilder.addOutputState` overload
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
Labels: enhancement

#5118 CORDA-2586: Publish corda-common-logging
  build.gradle
Labels: Backport

#5120 CORDA-2870 improve error messages for non composable types
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CorDappCustomSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ObjectSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/PropertyDescriptor.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeSimpleTypesTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/model/LocalTypeModelTests.kt
Labels: enhancement

#4798 CORDA-2639: CorDapp dependencies documentation
  docs/source/api-contract-constraints.rst
  docs/source/api-states.rst
  docs/source/cordapp-advanced-concepts.rst
Labels: docs

#5155 RELEASE - Fix release tools
  release-tools/jiraReleaseChecker.py
Labels: Release, bug

#5150 CORDA-2909 Build `CURRENT_MAJOR_RELEASE` from `build.gradle` in commons-logging
  common/logging/build.gradle
  common/logging/src/main/kotlin/net/corda/common/logging/Constants.kt
  common/logging/src/main/kotlin/net/corda/common/logging/CordaVersion.kt
  common/logging/src/main/template/kotlin/net/corda/common/logging/Constants.kt
Labels: enhancement
