Repository corda/corda, pull requests merged in 2019-06, with the labels that each got.

#5182 Docs update: fixed vaultQuery command in Hello World tutorial
  docs/source/hello-world-running.rst
Labels: docs

#5154 RELEASE - 4.1 release notes
  docs/source/release-notes.rst
Labels: Release, work in progress

#5227 CORDA-3015: Add StatePointer classes to corda-core-deterministic.
  core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
Labels: bug

#5229 CORDA-3017 - Fix release tooling when product name != jira project
  release-tools/testing/test-manager
Labels: Release, enhancement

#5215 CORDA-2999: Corrected network builder JAR url in docs
  docs/source/network-builder.rst
Labels: docs

#5208 ENT-3543 Update okhttp dependency
  build.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/http/HttpUtils.kt
Labels: Backport

#5207 ENT-3542 remove unused commons-codec dep
  node/build.gradle
Labels: Backport

#5206 ENT-3541 remove unused commons-fileupload dep
  node-api/build.gradle
Labels: Backport

#5168 ENT-3535 Update Hibernate dependency
  build.gradle
Labels: Backport

#5144 CORDA-2934 disable hibernate validator integration with hibernate (#5…
  docs/source/changelog.rst
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/HibernateConfiguration.kt
Labels: Backport

#5126 CORDA-2935: Align timeouts for CRL retrieval and TLS handshake
  node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt
  node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt
Labels: Backport

#5124 CORDA-2511 Upgrade notes for C4 need to include required minimum previous Corda version (#5039)
  docs/source/node-upgrade-notes.rst
Labels: Backport

#5241 CORDA-2871: Fine-tune compile vs runtime scopes for published deterministic jars.
  constants.properties
  core-deterministic/build.gradle
  core-deterministic/testing/verifier/build.gradle
  jdk8u-deterministic/build.gradle
  serialization-deterministic/build.gradle
Labels: bug, enhancement

#5260 Remove mention of hot swapping of cordapp config files
  docs/source/cordapp-build-systems.rst
Labels: docs
