Repository corda/corda, pull requests merged in 2019-12, with the labels that each got.

#5769 CORDA-3464: Also scan attachment:// URLs for custom serializers.
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt
  constants.properties
  core/build.gradle
  core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  core/src/test/kotlin/net/corda/core/internal/AsmTools.kt
  core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CurrantsySerializer.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CustomSerializerContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CustomSerializerRegistry.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/custom/CustomSerializerFlow.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithCustomSerializerTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/CustomCordapp.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt
Labels: bug

#5771 CORDA-3464: Also scan attachment:// URLs for custom serializers.
  build.gradle
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt
  constants.properties
  core/build.gradle
  core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  core/src/test/kotlin/net/corda/core/internal/AsmTools.kt
  core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CurrantsySerializer.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CustomSerializerContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CustomSerializerRegistry.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/custom/CustomSerializerFlow.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithCustomSerializerTest.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/CustomCordapp.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt
Labels: Backport, bug

#5789 ENM-866: Link to correct endpoints
  docs/source/network-map.rst
Labels: docs

#5804 ENT-4595: Delete SgxSupport from core-deterministic.
  core-deterministic/build.gradle
  core-deterministic/src/main/kotlin/net/corda/core/utilities/SgxSupport.kt
  core/src/main/kotlin/net/corda/core/utilities/SgxSupport.kt
Labels: enhancement

#5803 ENT-4595: Don't change existing archive classifiers for test artifacts.
  core/build.gradle
  serialization/build.gradle
Labels: bug

#5813 NOTICK: Refactor Gradle script for building Docker images.
  docker/build.gradle
Labels: bug

#5809 NOTICK: Remove buildscript block from Node's build.gradle.
  node/build.gradle
Labels: bug

#5602 Update UAT.md
  docs/source/corda-network/UAT.md
Labels: docs
