Repository corda/corda, pull requests merged in 2019-04, with the labels that each got.

#4971 CORDA-2817 Revert CORDA-2162 but modify Cash move to allow multiple m…
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
  core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt
  finance/contracts/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
  finance/contracts/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
  finance/contracts/src/test/kotlin/net/corda/finance/contracts/asset/ObligationTests.kt
Labels: bug

#4999 CORDA-2651 Check if resources are in classpath
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
Labels: bug

#4973 CORDA-2810 - more doc build cleanups
  docs/docs_builder/lexer-fix/.gitignore
  docs/docs_builder/lexer-fix/Dockerfile
  docs/docs_builder/lexer-fix/jvm.py
  docs/docs_builder/lexer-fix/readme.md
  docs/docs_builder/lexer-fix/test_kotlin.py
  docs/requirements.txt
  docs/source/app-upgrade-notes.rst
  docs/source/conf.py
  docs/source/contract-upgrade.rst
  docs/source/contributing-flow-state-machines.rst
  docs/source/contributing.rst
  docs/source/corda-configuration-file.rst
  docs/source/corda-nodes-index.rst
  docs/source/demobench.rst
  docs/source/deploying-a-node.rst
  docs/source/deterministic-modules.rst
  docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/twoparty/IOUFlowResponder.kt
  docs/source/flow-overriding.rst
  docs/source/hello-world-running.rst
  docs/source/key-concepts-djvm.rst
  docs/source/loadtesting.rst
  docs/source/node-administration.rst
  docs/source/release-notes.rst
  docs/source/running-a-node.rst
  docs/source/testnet-explorer-corda.rst
  docs/source/tut-two-party-flow.rst
  docs/source/tutorial-attachments.rst
  docs/source/tutorial-custom-notary.rst
  docs/source/tutorial-test-dsl.rst
  docs/source/writing-a-cordapp.rst
Labels: docs

#5001 CORDA-2848 relax fingerprinter strictness
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/TypeModellingFingerPrinterTests.kt
Labels: bug

#5007 CORDA-2848 backport
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/TypeModellingFingerPrinterTests.kt
Labels: Backport

#4783 CORDA-2456: Documentation around explicit upgrades
  docs/source/upgrading-cordapps.rst
Labels: docs

#5020 Backport/corda 2621/log level
  node/src/main/kotlin/net/corda/node/internal/artemis/BrokerJaasLoginModule.kt
Labels: Backport

#5018 CORDA-2456: Documentation around explicit upgrades (#4783)
  docs/source/upgrading-cordapps.rst
Labels: Backport

#5016 [CORDA-2522] Improve error reporting around failed flows
  core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/interceptors/DumpHistoryOnErrorInterceptor.kt
Labels: Backport

#5015 Backport/corda 2743/reconnecting rpc
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
  docs/source/clientrpc.rst
  node/src/integration-test/kotlin/net/corda/node/services/rpc/RandomFailingProxy.kt
  node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/DriverInternal.kt
Labels: Backport

#5014 CORDA-2633 Restructure evolution serialization errors to print reason first
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
Labels: Backport

#5032 Backport - Fix tut-two-party-flow kotlin docs + make both versions easier to read
  docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUFlowResponder.java
  docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/twoparty/IOUFlowResponder.kt
  docs/source/tut-two-party-flow.rst
Labels: Backport, docs

#5036 CORDA-2861: give the message executor its own artemis session and producer
  node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
Labels: Backport, bug

#5043 NOTICK - Add option to reset keyring for test-manager
  release-tools/testing/login_manager.py
  release-tools/testing/test-manager
Labels: enhancement

#5053 CORDA-2280 Automatic propagation of whitelisted to Signature Constraints
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
  docs/source/cordapp-constraint-migration.rst
  node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
Labels: enhancement

#5041 CORDA-2477 Improve Signature Constraints documentation
  core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
  core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt
  docs/source/api-contract-constraints.rst
  docs/source/app-upgrade-notes.rst
  docs/source/versioning.rst
  testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
Labels: docs

#5070 CORDA-2902: Remove the CanonicalizerPlugin from buildSrc.
  buildSrc/canonicalizer/build.gradle
  buildSrc/canonicalizer/src/main/groovy/CanonicalizerPlugin.groovy
  buildSrc/settings.gradle
  confidential-identities/build.gradle
  finance/contracts/build.gradle
  finance/workflows/build.gradle
  isolated/build.gradle
Labels: enhancement
