Repository corda/corda, pull requests merged in 2019-02, with the labels that each got.

#4696 Cherry pick finance changes
  docs/source/app-upgrade-notes.rst
  docs/source/changelog.rst
  docs/source/cordapp-build-systems.rst
  docs/source/generating-a-node.rst
  docs/source/hello-world-running.rst
  docs/source/testnet-explorer-corda.rst
  finance/build.gradle
  settings.gradle
Labels: Backport

#4723 [CORDA-2538] Updating the docs for tutorial cordapp to reflect Spring Boot changes
  docs/source/tutorial-cordapp.rst
Labels: Backport

#4720 [CORDA-2547] Migrate table of SimpleNotaryService
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
  node/src/main/resources/migration/node-core.changelog-master.xml
  node/src/main/resources/migration/node-notary.changelog-init.xml
  node/src/main/resources/migration/node-notary.changelog-master.xml
  node/src/main/resources/migration/node-notary.changelog-v2.xml
  node/src/main/resources/migration/vault-schema.changelog-master.xml
  node/src/main/resources/migration/vault-schema.changelog-v7.xml
Labels: Backport

#4647 CORDA-2509 - Updating release notes
  docs/make-docsite.sh
  docs/source/release-notes.rst
Labels: Release

#4752 DOCS - Changelog typo fix
  docs/source/changelog.rst
Labels: docs

#4758 CORDA-2505: bumped typesafe to a version that fixes NPE in their code
  constants.properties
Labels: bug

#4764 Fixed typo in bootstrapper doc; specify text for anchor
  docs/source/network-bootstrapper.rst
Labels: docs

#4775 CORDA-2623 - Add help screen to Network Builder CLI tool
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt
  tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/cli/CommandParsers.kt
Labels: enhancement

#4774 CORDA-2622 - Fix shell extensions
  tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt
Labels: bug

#4784 CORDA-2634 - Fix derivation of currentTargetVersion for abstract classes
  core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
  core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt
  core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt
  node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
Labels: bug

#4773 ENT-3053 Database connection pools leaking memory on every checkpoint
  build.gradle
  node-api/build.gradle
  node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
  node/build.gradle
  node/src/main/kotlin/net/corda/node/services/statemachine/FiberUtils.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
Labels: bug

#4791 [CORDA-2615] - Remove incorrect documentation
  docs/source/cordapp-build-systems.rst
Labels: Backport, docs

#4796 CORDA-2654: Repair the DJVM CLI tool.
  djvm/build.gradle
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Commands.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/NewCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Utilities.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistGenerateCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistShowCommand.kt
  djvm/shell/djvm
  djvm/shell/install
  djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
  djvm/src/main/kotlin/net/corda/djvm/source/ClassSource.kt
  docs/source/key-concepts-djvm.rst
Labels: bug

#4799 CORDA-2654: Repair the DJVM CLI tool. (#4796)
  djvm/build.gradle
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Commands.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/NewCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Utilities.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistGenerateCommand.kt
  djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistShowCommand.kt
  djvm/shell/djvm
  djvm/shell/install
  djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
  djvm/src/main/kotlin/net/corda/djvm/source/ClassSource.kt
  docs/source/key-concepts-djvm.rst
Labels: Backport, bug, docs

#4800 CORDA-2664 - Update Docker docs
  docs/source/docker-image.rst
Labels: docs

#4801 CORDA-2664 - Update Docker docs
  docs/source/docker-image.rst
Labels: Backport, docs

#4802 NOTICK - Docker: point to release images instead of snapshot
  docs/source/docker-image.rst
Labels: docs

#4804 CORDA-2667: Fix DJVM SourceClassLoader for ASM.
  djvm/build.gradle
  djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt
  djvm/src/main/kotlin/net/corda/djvm/rewiring/ClassRewriter.kt
  djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt
  djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
Labels: bug

#4803 CORDA-2610: Internal APIs made much clearer in API doc page
  docs/source/corda-api.rst
Labels: Backport, docs

#4794 ENT-3017: TestCordapp – use Gradle tooling API for builds
  build.gradle
  testing/node-driver/build.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
Labels: bug

#4806 CORDA-2669 - Reintroduce pendingFlowsCount
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/RpcHelpers.kt
  node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
  tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
Labels: bug

#4807 CORDA-2669 - Reintroduce pendingFlowsCount (#4806)
  .ci/api-current.txt
  core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/RpcHelpers.kt
  node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
  tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
Labels: Backport, bug

#4811 CORDA-2671: Remove broken ExplorerSimulator from Node Explorer.
  docs/source/node-explorer.rst
  tools/explorer/README.md
  tools/explorer/build.gradle
  tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
  tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
  tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
Labels: bug

#4814 ENT-3128: Tidy up DemoBench's "built-in CorDapp" management.
  tools/demobench/src/main/kotlin/net/corda/demobench/plugin/CordappController.kt
Labels: enhancement

#4819 CORDA-2665: Updated OwnableState relevancy check put back to V3 version
  node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
  node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Labels: bug
