Repository corda/corda, pull requests merged in 2020-07, with the labels that each got.

#6435 CORDA-3892: Upgrade Gradle 5.4.1 -> 5.6.4.
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, technical debt

#6430 NOTICK: Fix some Gradle technical debt.
  build.gradle
  core-tests/build.gradle
  deterministic.gradle
  experimental/avalanche/build.gradle
  java8.gradle
  node/build.gradle
  node/capsule/build.gradle
  samples/irs-demo/cordapp/build.gradle
  serialization-djvm/build.gradle
  testing/testserver/testcapsule/build.gradle
  tools/demobench/build.gradle
  tools/error-tool/build.gradle
  tools/explorer/build.gradle
  tools/explorer/capsule/build.gradle
  tools/network-builder/build.gradle
  tools/shell-cli/build.gradle
  tools/shell/build.gradle
Labels: technical debt

#6439 CORDA-3892: Revert back to Gradle 5.4.1 to fix "clean" task.
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#6448 CORDA-3892: Upgrade to Gradle 5.6.4 again, with build fixes.
  build.gradle
  core-tests/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  node/build.gradle
Labels: enhancement

#6452 NOTICK: Avoid configuring more Gradle tasks in the deterministic modules.
  core-deterministic/build.gradle
  deterministic.gradle
  jdk8u-deterministic/build.gradle
  node/capsule/build.gradle
  serialization-deterministic/build.gradle
Labels: enhancement, technical debt

#6457 CORDA-3906: Allow usage of SchedulableState in deterministic CorDapps.
  core/src/main/kotlin/net/corda/core/contracts/Structures.kt
  core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
Labels: enhancement

#6463 CORDA-3909: Upgrade to Corda Gradle plugins 5.0.11.
  build.gradle
  constants.properties
Labels: enhancement

#6481 NOTICK: OS 4.5 -> OS 4.6 merge
  .ci/dev/compatibility/JenkinsfileJDK11Azul
  .ci/dev/nightly-regression/Jenkinsfile
  .ci/dev/publish-api-docs/Jenkinsfile
  .ci/dev/regression/Jenkinsfile
  Jenkinsfile
  build.gradle
  docs/build.gradle
  settings.gradle
  testing/node-driver/src/main/java/net/corda/testing/driver/SharedMemoryIncremental.java
Labels: Upstream Merge

#6485 NOTICK: OS 4.5 to OS 4.6 merge
  node/src/test/kotlin/net/corda/node/internal/AbstractNodeTests.kt
  testing/test-common/src/main/kotlin/net/corda/testing/common/internal/Thoroughness.kt
Labels: Upstream Merge
