Repository corda/corda, pull requests merged in 2020-01, with the labels that each got.

#5825 ENT-4652: Provide an "attachment fixup" mechanism to repair broken transactions.
  core/src/main/kotlin/net/corda/core/contracts/ContractAttachment.kt
  core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
  core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt
  core/src/main/kotlin/net/corda/core/internal/CordappFixupInternal.kt
  core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
  core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
  core/src/main/kotlin/net/corda/core/node/services/TransactionVerifierService.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/MissingSerializerException.kt
  core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
  core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
  docs/source/changelog.rst
  node/src/integration-test/kotlin/net/corda/contracts/fixup/dependent/DependentContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/fixup/dependent/DependentData.kt
  node/src/integration-test/kotlin/net/corda/contracts/fixup/dependent/DependentDataSerializer.kt
  node/src/integration-test/kotlin/net/corda/contracts/fixup/dependent/StandAloneDataSerializer.kt
  node/src/integration-test/kotlin/net/corda/contracts/fixup/standalone/StandAloneContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/fixup/standalone/StandAloneData.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CustomSerializerContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/custom/CustomSerializerRegistry.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/missing/CustomData.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/missing/MissingSerializerContract.kt
  node/src/integration-test/kotlin/net/corda/flows/fixup/CordappFixupFlow.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/missing/CustomDataSerializer.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/missing/MissingSerializerBuilderFlow.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/missing/MissingSerializerFlow.kt
  node/src/integration-test/kotlin/net/corda/node/Assertions.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithCordappFixupTest.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithCustomSerializerTest.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithMissingCustomSerializerTest.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/internal/Node.kt
  node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
  node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderInternal.kt
  node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
  node/src/main/kotlin/net/corda/node/services/transactions/InMemoryTransactionVerifierService.kt
  samples/simm-valuation-demo/contracts-states/build.gradle
  samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/contracts/CordappDependencies.kt
  samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/contracts/IRSState.kt
  samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/contracts/PortfolioState.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ObjectSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/RemoteSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/CustomCordapp.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
Labels: bug

#5859 ENT-4652: Add unit tests for parsing attachment fix-up rules.
  node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
  node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
Labels: bug

#5858 CORDA-3523: DJVM custom serializers and whitelists
  constants.properties
  core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
  jdk8u-deterministic/build.gradle
  node/src/integration-test/kotlin/net/corda/contracts/djvm/attachment/SandboxAttachmentContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/djvm/broken/NonDeterministicContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/djvm/crypto/DeterministicCryptoContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/djvm/whitelist/DeterministicWhitelistContract.kt
  node/src/integration-test/kotlin/net/corda/contracts/djvm/whitelist/WhitelistData.kt
  node/src/integration-test/kotlin/net/corda/flows/djvm/whitelist/DeterministicWhitelistFlow.kt
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicContractCryptoTest.kt
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicContractWithCustomSerializerTest.kt
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicContractWithSerializationWhitelistTest.kt
  node/src/main/kotlin/net/corda/node/internal/djvm/DeterministicVerifier.kt
  node/src/main/kotlin/net/corda/node/internal/djvm/Serializer.kt
  node/src/main/kotlin/net/corda/node/services/transactions/DeterministicVerifierFactoryService.kt
  serialization-djvm/deserializers/src/main/kotlin/net/corda/serialization/djvm/deserializers/CorDappCustomDeserializer.kt
  serialization-djvm/deserializers/src/main/kotlin/net/corda/serialization/djvm/deserializers/MergeWhitelists.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/AMQPSerializationScheme.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/Serialization.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxBitSetSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxCertPathSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxCorDappCustomSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxCurrencySerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxDurationSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxEnumSetSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxInputStreamSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxInstantSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxLocalDateSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxLocalDateTimeSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxLocalTimeSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxMonthDaySerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxOffsetDateTimeSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxOffsetTimeSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxOpaqueBytesSubSequenceSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxOptionalSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxPeriodSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxPublicKeySerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxToStringSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxX509CRLSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxX509CertificateSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxYearMonthSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxYearSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxZoneIdSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxZonedDateTimeSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/Serializers.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/Assertions.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeComposedCustomDataTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeCustomGenericDataTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeWithCustomSerializerTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeWithObjectCustomSerializerTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeWithSerializationWhitelistTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/LocalSerialization.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestBase.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CorDappCustomSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializer.kt
Labels: enhancement

#5833 ENT-4601 Public API to run external operations from a flow
  .ci/api-current.txt
  core-tests/src/test/java/net/corda/coretests/flows/FlowExternalOperationInJavaTest.java
  core-tests/src/test/kotlin/net/corda/coretests/flows/AbstractFlowExternalOperationTest.kt
  core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalAsyncOperationTest.kt
  core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationStartFlowTest.kt
  core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationTest.kt
  core/src/main/kotlin/net/corda/core/flows/FlowExternalOperations.kt
  core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
  core/src/main/kotlin/net/corda/core/internal/FlowAsyncOperation.kt
  core/src/main/kotlin/net/corda/core/internal/ServiceHubCoreInternal.kt
  core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
  core/src/main/kotlin/net/corda/core/internal/notary/SinglePartyNotaryService.kt
  docs/source/api-flows.rst
  docs/source/contributing-flow-state-machines.rst
  docs/source/corda-configuration-file.rst
  docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/flowstatemachines/TutorialFlowAsyncOperation.kt
  node/src/integration-test-slow/kotlin/net/corda/node/services/statemachine/StatemachineErrorHandlingTest.kt
  node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
  node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
  node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt
  node/src/main/kotlin/net/corda/node/services/rpc/CheckpointDumperImpl.kt
  node/src/main/kotlin/net/corda/node/services/statemachine/TransitionExecutorImpl.kt
  node/src/test/kotlin/net/corda/node/services/statemachine/FlowAsyncOperationTests.kt
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt
  tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt
Labels: enhancement

#5874 CORDA-3552: Reuse a single SerializerFactory when deserialising into the DJVM sandbox.
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/AMQPSerializationScheme.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/SandboxSerializationSchemeBuilder.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/Serialization.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/LocalTypeModelTest.kt
Labels: bug

#5900 ENT-4911: Split network verifier's sealed CorDapps into separate packages,
  samples/network-verifier/contracts/src/main/kotlin/net/corda/verification/contracts/CommsContracts.kt
  samples/network-verifier/contracts/src/main/kotlin/net/corda/verification/contracts/NotaryTestContracts.kt
  samples/network-verifier/workflows/src/main/kotlin/net/corda/verification/flows/TestCommsFlow.kt
  samples/network-verifier/workflows/src/main/kotlin/net/corda/verification/flows/TestNotaryFlow.kt
  samples/network-verifier/workflows/src/test/kotlin/net/corda/configsample/TestCommsFlowInitiatorTest.kt
Labels: bug

#5896 CORDA-3536: Load DJVM serialization types more precisely to avoid runtime warnings.
  constants.properties
  serialization-djvm/deserializers/src/main/kotlin/net/corda/serialization/djvm/deserializers/CheckEnum.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/SandboxSerializationSchemeBuilder.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/SandboxSerializerFactoryFactory.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/Serialization.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxCollectionSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxEnumSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxMapSerializer.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/LocalTypeModelTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestBase.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/RemoteSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformsSchema.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/WhitelistBasedTypeModelConfiguration.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeModel.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeLoader.kt
Labels: bug

#5901 CORDA-3025: Permissions template for a read-only user
  docs/source/shell.rst
Labels: docs

#5910 CORDA-3377: Upgrade to DJVM 1.0-RC09.
  constants.properties
Labels: bug

#5903 [EG-75] Not handled exception when NetworkMap not accessible
  node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
Labels: awaiting response
