Repository corda/corda, pull requests merged in 2020-02, with the labels that each got.

#5948 ENT-4933: Document `notary.etaMessageThresholdSeconds`
  docs/source/corda-configuration-file.rst
Labels: docs

#5954 ENT-4921: Ensure that CorDapp classloader is not lost with graceful reconnect.
  client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
Labels: bug

#5958 Merge from OS 4.4 up to 117108f.
  client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
Labels: bug

#5960 ENT-4652: Tighten Groovy code for writing META-INF/Cordapp-Dependencies.
  samples/simm-valuation-demo/contracts-states/build.gradle
Labels: bug, trivial

#5967 NOTICK: Add timeouts to serialization-djvm tests too.
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeOffsetTimeTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestBase.kt
Labels: enhancement

#5970 NOTICK: Update Gradle files for DeteKt plugins.
  build.gradle
  detekt-plugins/build.gradle
Labels: enhancement

#5962 [EG-65] Improved error reporting on stdout
  common/logging/src/main/kotlin/net/corda/common/logging/ExceptionsErrorCodeFunctions.kt
  common/logging/src/test/kotlin/net/corda/commmon/logging/WalkExceptionCausedByListTest.kt
Labels: bug

#5976 CORDA-3618: Upgrade to Corda Gradle plugins 5.0.8.
  constants.properties
Labels: enhancement

#5979 NOTICK: Always use configured version of deterministic-rt.jar.
  serialization-djvm/build.gradle
Labels: bug

#5975 CORDA-3617: Remove Schedulable states from core-deterministic.
  core/src/main/kotlin/net/corda/core/contracts/Structures.kt
Labels: bug

#5978 NOTICK: Update Gradle scripts for deterministic modules.
  core-deterministic/build.gradle
  core-deterministic/testing/build.gradle
  core-deterministic/testing/data/build.gradle
  core-deterministic/testing/verifier/build.gradle
  serialization-deterministic/build.gradle
  serialization-djvm/deserializers/build.gradle
Labels: enhancement

#5971 NOTICK: Add missing test for deserializing Duration for DJVM.
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeDurationTest.kt
Labels: bug

#5988 NOTICK: Tidy up driver shutdown so that resources are always released on error.
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: bug

#5989 NOTICK: Fix more Gradle technical debt.
  build.gradle
  core-deterministic/build.gradle
  core-deterministic/testing/build.gradle
  core-deterministic/testing/data/build.gradle
  serialization-deterministic/build.gradle
Labels: bug

#5993 NOTICK: Fix potential infinite loop when a SecurityManager is installed.
  testing/node-driver/src/main/java/net/corda/testing/driver/SharedMemoryIncremental.java
Labels: bug
