Repository corda/corda, pull requests merged in 2020-05, with the labels that each got.

#6186 CORDA-3754 Make TransactionBuilder's input references deep copied on copy.
  core-tests/src/test/kotlin/net/corda/coretests/transactions/TransactionBuilderTest.kt
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
Labels: Triaged

#6209 CORDA-3758: Ensure that providerMap is immutable, at the very least.
  core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt
Labels: bug

#6208 CORDA-3750: Delete unwanted methods from the deterministic artifacts.
  core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/custom/PrivateKeySerializer.kt
Labels: bug

#6219 CORDA-3738: Upgrade to DJVM 1.1-RC03.
  constants.properties
  node/src/main/kotlin/net/corda/node/services/transactions/DeterministicVerifierFactoryService.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestBase.kt
Labels: enhancement

#6222 CORDA-3768: Upgrade to Corda Gradle Plugins 5.0.9.
  constants.properties
Labels: enhancement

#6193 CORDA-3750: Reimplement Corda's Crypto object for use inside the sandbox.
  constants.properties
  node/build.gradle
  node/djvm/src/main/kotlin/net/corda/node/djvm/LtxFactory.kt
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicCashIssueAndPaymentTest.kt
  node/src/main/java/sandbox/java/lang/CharSequence.java
  node/src/main/java/sandbox/java/lang/Comparable.java
  node/src/main/java/sandbox/java/lang/Number.java
  node/src/main/java/sandbox/java/math/BigInteger.java
  node/src/main/java/sandbox/java/security/Key.java
  node/src/main/java/sandbox/java/security/KeyPair.java
  node/src/main/java/sandbox/java/security/PrivateKey.java
  node/src/main/java/sandbox/java/security/PublicKey.java
  node/src/main/java/sandbox/java/security/spec/AlgorithmParameterSpec.java
  node/src/main/java/sandbox/java/util/ArrayList.java
  node/src/main/java/sandbox/java/util/List.java
  node/src/main/java/sandbox/net/corda/core/crypto/DJVM.java
  node/src/main/java/sandbox/net/corda/core/crypto/DJVMPublicKey.java
  node/src/main/java/sandbox/org/bouncycastle/asn1/ASN1Encodable.java
  node/src/main/java/sandbox/org/bouncycastle/asn1/ASN1Object.java
  node/src/main/java/sandbox/org/bouncycastle/asn1/x509/AlgorithmIdentifier.java
  node/src/main/java/sandbox/org/bouncycastle/asn1/x509/SubjectPublicKeyInfo.java
  node/src/main/kotlin/net/corda/node/internal/djvm/Serializer.kt
  node/src/main/kotlin/net/corda/node/services/transactions/DeterministicVerifierFactoryService.kt
  node/src/main/kotlin/sandbox/net/corda/core/crypto/Crypto.kt
  node/src/main/kotlin/sandbox/net/corda/core/crypto/SecureHash.kt
  node/src/main/kotlin/sandbox/net/corda/core/crypto/SignatureScheme.kt
  node/src/main/kotlin/sandbox/net/corda/core/crypto/TransactionSignature.kt
  node/src/main/kotlin/sandbox/net/corda/core/crypto/internal/ProviderMap.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxPublicKeySerializer.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializePublicKeyTest.kt
Labels: enhancement
