Repository corda/corda, pull requests merged in 2020-08, with the labels that each got.

#6603 CORDA-3936: Add a fallback mechanism for Enums incorrectly serialised using their toString() method.
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/SandboxSerializerFactoryFactory.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/Serialization.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxEnumSerializer.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeRemoteCustomisedEnumTest.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/TestHelpers.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EnumEvolutionSerializer.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/WhitelistBasedTypeModelConfiguration.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeModel.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumToStringFallbackTest.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnvelopeHelpers.kt
Labels: bug

#6608 NOTICK: Merge from OS 4.4 into OS 4.5
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxEnumSerializer.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeRemoteCustomisedEnumTest.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumToStringFallbackTest.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnvelopeHelpers.kt
Labels: Upstream Merge

#6609 NOTICK: Merge OS 4.5 to OS 4.6 up to 38cad33.
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxEnumSerializer.kt
  serialization-djvm/src/test/kotlin/net/corda/serialization/djvm/DeserializeRemoteCustomisedEnumTest.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumTests.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumToStringFallbackTest.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnvelopeHelpers.kt
Labels: Upstream Merge

#6591 CORDA-3984: Update to DJVM 1.1.1 to fix multi-release jars on Java 11.
  constants.properties
Labels: bug

#6621 CORDA-3987: Upgrade to Corda Gradle plugins 5.0.12.
  constants.properties
Labels: enhancement

#6584 CORDA-3931 - Fixed a bug which was preventing the custom JVM arguments from being picked up when the command line "-f" flag was used
  node/capsule/src/main/java/CordaCaplet.java
Labels: bug
