Repository corda/corda, pull requests merged in 2020-03, with the labels that each got.

#5994 CORDA-3638: Allow CordaFuture to complete even if an Error is thrown.
  core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
Labels: bug

#6022 Fix the operator used by the notEqual predicate
  core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
  docs/source/changelog.rst
  node/src/test/kotlin/net/corda/node/services/vault/QueryCriteriaUtilsBuilderTest.kt
Labels: bug

#6014 CORDA-3644: Scan the CorDapp classloader directly for SerializationWhitelist.
  docs/source/example-code/src/integration-test/java/net/corda/docs/java/tutorial/test/TutorialFlowAsyncOperationTest.java
  docs/source/example-code/src/integration-test/kotlin/net/corda/docs/kotlin/tutorial/test/TutorialFlowAsyncOperationTest.kt
  node/src/integration-test/kotlin/net/corda/node/logging/ErrorCodeLoggingTests.kt
  node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
  samples/irs-demo/cordapp/workflows-irs/build.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: bug

#6021 CORDA-3377: Upgrade to DJVM 1.0-RC10.
  constants.properties
Labels: bug

#6028 Delete extra characters at end of key-concepts-ledger.rst
  docs/source/key-concepts-ledger.rst
Labels: docs, trivial

#6033 [NOTICK] The list added for Bugs and Storys without Epic link
  docs/source/release-notes.rst
Labels: docs

#6032 CORDA-3644: Add Corda-Test attribute to test artifacts' MANIFEST.MF
  client/mock/build.gradle
  testing/cordapps/dbfailure/dbfcontracts/build.gradle
  testing/cordapps/dbfailure/dbfworkflows/build.gradle
  testing/node-driver/build.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
  testing/smoke-test-utils/build.gradle
  testing/test-cli/build.gradle
  testing/test-common/build.gradle
  testing/test-db/build.gradle
  testing/test-utils/build.gradle
Labels: bug

#6042 NOTICK: Better use of generics for DJVM Collection and Map serializers.
  serialization-djvm/deserializers/src/main/kotlin/net/corda/serialization/djvm/deserializers/CreateCollection.kt
  serialization-djvm/deserializers/src/main/kotlin/net/corda/serialization/djvm/deserializers/CreateMap.kt
  serialization-djvm/deserializers/src/main/kotlin/net/corda/serialization/djvm/deserializers/OptionalDeserializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxCollectionSerializer.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/serializers/SandboxMapSerializer.kt
Labels: enhancement, trivial

#6047 CORDA-3644: Add Corda-Testing tag to core-test-utils manifest.
  testing/core-test-utils/build.gradle
Labels: bug

#6065 NOTICK: Prevent learning the location of a Class inside sandbox.
  core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
Labels: bug

#6071 CORDA-3377: Upgrade to DJVM 1.0.
  constants.properties
Labels: enhancement

#6077 Prevent Quasar from instrumenting classes that belong to AttachmentsClassLoader.
  node/build.gradle
  node/capsule/build.gradle
  testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Labels: enhancement, work in progress

#6080 CORDA-3668: Prevent AttachmentURLConnection from assigning ALL_PERMISSIONS.
  core-tests/src/test/kotlin/net/corda/coretests/transactions/AttachmentsClassLoaderTests.kt
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
Labels: bug

#6102 CORDA-3680: Add CorDapp custom serialisers to Driver's in-process nodes.
  node-api/src/main/kotlin/net/corda/nodeapi/internal/rpc/client/AMQPClientSerializationScheme.kt
  node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPServerSerializationScheme.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithCustomSerializerTest.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithMissingCustomSerializerTest.kt
  testing/core-test-utils/src/main/kotlin/net/corda/coretesting/internal/InternalSerializationTestHelpers.kt
Labels: bug

#6098 CORDA-3680: Add CorDapp custom serialisers to Driver's in-process nodes.
  client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithCustomSerializerTest.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithMissingCustomSerializerTest.kt
  node/src/main/kotlin/net/corda/node/serialization/amqp/AMQPServerSerializationScheme.kt
  testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt
Labels: bug

#6119 ENT-4967: Allow quasar_classifier to be either null or an empty string.
  node/capsule/build.gradle
  testing/testserver/testcapsule/build.gradle
Labels: enhancement, trivial
