Repository corda/corda, pull requests merged in 2020-06, with the labels that each got.

#6215 update docker version
  tools/network-builder/src/main/resources/node-Dockerfile
Labels: community

#6338 CORDA-3738: Upgrade to DJVM 1.1.
  constants.properties
Labels: enhancement

#6360 CORDA-3831: Prevent CordappImpl TEST_INSTANCE from crashing node.
  core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
Labels: bug

#6359 ENT-5430: Fix deserialisation of commands containing generic types.
  node/src/integration-test/kotlin/net/corda/contracts/serialization/generics/DataObject.kt
  node/src/integration-test/kotlin/net/corda/contracts/serialization/generics/GenericTypeContract.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/generics/GenericTypeFlow.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithGenericTypeTest.kt
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicContractWithGenericTypeTest.kt
  serialization-djvm/src/main/kotlin/net/corda/serialization/djvm/SandboxSerializerFactoryFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt
  serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt
  serialization/src/test/kotlin/net/corda/serialization/internal/amqp/TypeModellingFingerPrinterTests.kt
Labels: bug

#6387 ENT-5430: Increase test coverage when serializing Optional fields.
  node/src/integration-test/kotlin/net/corda/contracts/serialization/generics/GenericTypeContract.kt
  node/src/integration-test/kotlin/net/corda/flows/serialization/generics/GenericTypeFlow.kt
  node/src/integration-test/kotlin/net/corda/node/ContractWithGenericTypeTest.kt
  node/src/integration-test/kotlin/net/corda/node/services/DeterministicContractWithGenericTypeTest.kt
Labels: trivial

#6352 EG-2292 Membership State for Business Networks
  build.gradle
  business-networks/contracts/build.gradle
  business-networks/contracts/src/main/kotlin/net/corda/bn/schemas/MembershipStateSchemaV1.kt
  business-networks/contracts/src/main/kotlin/net/corda/bn/states/MembershipState.kt
  business-networks/contracts/src/main/resources/membership-state-schema-v1.changelog-init.xml
  business-networks/contracts/src/main/resources/membership-state-schema-v1.changelog-master.xml
  business-networks/contracts/src/test/kotlin/net/corda/bn/states/MembershipStateTest.kt
  settings.gradle
Labels: enhancement

#6406 INRFA-415: Publish empty source and JavaDoc for deterministic modules.
  core-deterministic/README.md
  core-deterministic/build.gradle
  serialization-deterministic/README.md
  serialization-deterministic/build.gradle
Labels: enhancement
