Repository corda/corda, pull requests merged in 2022-05, with the labels that each got.

#7177 NOTICK: CC4.9->CC4.10 merge
  .ci/dev/regression/Jenkinsfile
  build.gradle
  config/dev/log4j2.xml
  constants.properties
  docker/src/docker/Dockerfile
  docker/src/docker/Dockerfile-debug
  docker/src/docker/DockerfileAL
  node/build.gradle
  node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
  testing/test-common/src/main/resources/log4j2-test.xml
Labels: Upstream Merge

#7156 CORDA-4257: Do not emit warning when StatePointer.isResolved = false
  core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
Labels: Triaged

#7172 ENT-6532: Close AttachmentsClassLoader on eviction to avoid leaking file descriptors.
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
Labels: bug

#7179 NOTICK: Merge from OS 4.8 up to 91ef44d
  core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
  node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
  node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
Labels: Upstream Merge

#7178 NOTICK - Cross link Arch V1 to the Arch V2 repo
  README.md
Labels: docs
